---
permalink: cloud-connector/config-intro-concept.html 
sidebar: sidebar 
keywords: Cloud Connector configuration 
summary: 'Une fois l"installation effectuée, vous pouvez configurer l"application SANtricity Cloud Connector via l"assistant de configuration. L"assistant de configuration s"affiche après vous être connecté au Cloud Connector de SANtricity.' 
---
= Configurez pour la première fois SANtricity Cloud Connector
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Une fois l'installation effectuée, vous pouvez configurer l'application SANtricity Cloud Connector via l'assistant de configuration. L'assistant de configuration s'affiche après vous être connecté au Cloud Connector de SANtricity.



== Connectez-vous pour la première fois à SANtricity Cloud Connector

Lors de la première initialisation du SANtricity Cloud Connector pour la première fois, vous devez saisir un mot de passe par défaut pour accéder à l'application.

Vérifiez que vous avez accès à un navigateur connecté à Internet.

.Étapes
. Ouvrez un navigateur pris en charge.
. Se connecter au serveur SANtricity Cloud Connector configuré (par exemple, `+http://localhost:8080/+`).
+
La page de connexion initiale de l'application SANtricity Cloud Connector s'affiche.

. Dans le champ Mot de passe administrateur, entrez le mot de passe par défaut de `password`.
. Cliquez sur *connexion*.
+
L'assistant de configuration de SANtricity Cloud Connector s'affiche.





== Utilisation de l'assistant de configuration

L'assistant de configuration s'affiche lors de la connexion initiale au connecteur SANtricity Cloud Connector.

L'assistant de configuration vous permet de configurer le mot de passe d'administrateur, les informations d'identification de gestion de connexion de proxy de services Web, le type de cible de sauvegarde souhaité et la phrase de passe de chiffrement pour SANtricity Cloud Connector.



=== Étape 1 : définissez le mot de passe administrateur

Vous pouvez personnaliser le mot de passe utilisé pour les connexions suivantes vers SANtricity Cloud Connector à l'aide de la page définir un mot de passe administrateur.

L'établissement d'un mot de passe via la page définir le mot de passe de l'administrateur remplace de manière efficace le mot de passe par défaut utilisé lors de la connexion initiale de l'application SANtricity Cloud Connector.

.Étapes
. Sur la page définir le mot de passe administrateur, entrez le mot de passe de connexion souhaité pour SANtricity Cloud Connector dans le champ *Entrez le nouveau mot de passe administrateur*.
. Dans le champ *saisissez à nouveau le nouveau mot de passe administrateur*, saisissez à nouveau le mot de passe du premier champ.
. Cliquez sur *Suivant*.
+
La configuration du mot de passe pour SANtricity Cloud Connector est acceptée et la page de phrase secrète est affichée sous l'assistant de configuration.

+

NOTE: Le mot de passe administrateur défini par l'utilisateur n'est défini que lorsque vous avez terminé l'assistant de configuration.





=== Étape 2 : définir la phrase de passe

Dans la page entrer la phrase de passe de cryptage, vous pouvez spécifier une phrase de passe alphanumérique comprise entre 8 et 32 caractères.

Une phrase secrète définie par l'utilisateur est requise dans le cadre de la clé de chiffrement des données utilisée par l'application SANtricity Cloud Connector.

.Étapes
. Dans le champ *define a pass phrase*, saisissez la phrase de passe souhaitée.
. Dans le champ *saisissez à nouveau votre phrase de passe*, saisissez à nouveau la phrase de passe du premier champ.
. Cliquez sur *Suivant*.
+
La phrase de passe saisie pour l'application SANtricity Cloud Connector est acceptée et la page Sélectionner le type cible de l'assistant de configuration s'affiche.





=== Étape 3 : sélectionnez le type de cible

Les fonctionnalités de sauvegarde et de restauration sont disponibles pour les types de cibles Amazon S3, AltaVault et StorageGRID via SANtricity Cloud Connector. Vous pouvez spécifier le type de cible de stockage souhaité pour l'application SANtricity Cloud Connector, dans la page Sélectionner le type cible.

Vérifiez que vous disposez de l'un des éléments suivants : point de montage AltaVault, compte Amazon AWS ou compte StorageGRID.

.Étapes
. Dans le menu déroulant, sélectionnez l'une des options suivantes :
+
** Amazon AWS
** AltaVault
** StorageGRID
+
Une page Type cible pour l'option sélectionnée s'affiche dans l'Assistant de configuration.



. Consultez les instructions de configuration appropriées pour AltaVault, Amazon AWS ou StorageGRID.




==== Configurez l'appliance AltaVault

Après avoir sélectionné l'option d'appliance AltaVault sous la page Sélectionner le type cible, les options de configuration du type cible AltaVault s'affichent.

.Avant de commencer
* Le chemin de montage NFS est disponible pour une appliance AltaVault.
* Vous avez spécifié l'appliance AltaVault comme type cible.


.Étapes
. Dans le champ *NFS Mount Path* , entrez le point de montage pour le type de cible AltaVault.
+

NOTE: Les valeurs du champ *NFS Mount Path* doivent suivre le format du chemin Linux.

. Cochez la case *Enregistrer une sauvegarde de la base de données de configuration sur cette cible* pour créer une sauvegarde de la base de données de configuration sur le type cible sélectionné.
+

NOTE: Si une configuration de base de données existante est détectée sur le type cible spécifié lors du test de la connexion, vous pouvez remplacer les informations de configuration de base de données existantes sur l'hôte SANtricity Cloud Connector par les nouvelles informations de sauvegarde saisies dans l'assistant de configuration.

. Cliquez sur *Tester la connexion* pour tester la connexion pour les paramètres AltaVault spécifiés.
. Cliquez sur *Suivant*.
+
Le type cible spécifié pour SANtricity Cloud Connector est accepté et la page proxy de services Web s'affiche dans l'assistant de configuration.

. Passez à l'« étape 4 : connexion au proxy de services Web ».




==== Configurez le compte Amazon AWS

Après avoir sélectionné l'option Amazon AWS sous la page Sélectionner le type de cible, les options de configuration du type de cible Amazon AWS s'affichent.

.Avant de commencer
* Vous avez établi un compte Amazon AWS.
* Vous avez spécifié Amazon AWS comme type de cible.


.Étapes
. Dans le champ *ID de clé d'accès*, entrez l'ID d'accès pour la cible Amazon AWS.
. Dans le champ *clé d'accès secrète*, saisissez la clé d'accès secrète pour la cible.
. Dans le champ *Nom du compartiment*, entrez le nom du compartiment pour la cible.
. Cochez la case *Enregistrer une sauvegarde de la base de données de configuration sur cette cible* pour créer une sauvegarde de la base de données de configuration sur le type cible sélectionné.
+

NOTE: Il est recommandé d'activer ce paramètre pour vous assurer que les données de la cible de sauvegarde peuvent être restaurées en cas de perte de la base de données.

+

NOTE: Si une configuration de base de données existante est détectée sur le type cible spécifié lors du test de la connexion, vous pouvez remplacer les informations de configuration de base de données existantes sur l'hôte SANtricity Cloud Connector par les nouvelles informations de sauvegarde saisies dans l'assistant de configuration.

. Cliquez sur *Tester la connexion* pour vérifier les informations d'identification Amazon AWS saisies.
. Cliquez sur *Suivant*.
+
Le type cible spécifié pour SANtricity Cloud Connector est accepté, et la page proxy de services Web s'affiche sous l'assistant de configuration.

. Passez à l'« étape 4 : connexion au proxy de services Web ».




==== Configurez le compte StorageGRID

Après avoir sélectionné l'option StorageGRID sous la page Sélectionner le type cible, les options de configuration du type cible StorageGRID s'affichent.

.Avant de commencer
* Vous avez créé un compte StorageGRID.
* Vous avez signé un certificat StorageGRID avec le magasin de clés SANtricity Cloud Connector.
* Vous avez spécifié StorageGRID comme type cible.


.Étapes
. Dans le champ *URL*, entrez l'URL du service cloud Amazon S3
. Dans le champ *ID de clé d'accès*, saisissez l'ID d'accès pour la cible S3.
. Dans le champ *clé d'accès secrète*, saisissez la clé d'accès secrète pour la cible S3.
. Dans le champ *Nom du compartiment*, entrez le nom du compartiment pour la cible S3.
. Pour utiliser l'accès au style de chemin d'accès, cochez la case *utiliser l'accès au style de chemin d'accès*.
+

NOTE: Si cette option n'est pas cochée, l'accès de type hôte virtuel est utilisé.

. Cochez la case *Enregistrer une sauvegarde de la base de données de configuration sur cette cible* pour créer une sauvegarde de la base de données de configuration sur le type cible sélectionné.
+

NOTE: Il est recommandé d'activer ce paramètre pour vous assurer que les données de la cible de sauvegarde peuvent être restaurées en cas de perte de la base de données.

+

NOTE: Si une configuration de base de données existante est détectée sur le type cible spécifié lors du test de la connexion, vous pouvez remplacer les informations de configuration de base de données existantes sur l'hôte SANtricity Cloud Connector par les nouvelles informations de sauvegarde saisies dans l'assistant de configuration.

. Cliquez sur *Tester la connexion* pour vérifier les informations d'identification S3 saisies.
+

NOTE: Certains comptes compatibles S3 peuvent nécessiter des connexions HTTP sécurisées. Pour plus d'informations sur le placement d'un certificat StorageGRID dans le magasin de clés, reportez-vous à la section link:install-intro-concept.html#add-storagegrid-certificate-into-a-keystore["Ajoutez le certificat StorageGRID dans un magasin de clés"].

. Cliquez sur *Suivant*.
+
Le type cible spécifié pour SANtricity Cloud Connector est accepté et la page proxy de services Web s'affiche sous l'assistant de configuration.

. Passez à l'« étape 4 : connexion au proxy de services Web ».




=== Étape 4 : connexion au proxy de services Web

Les informations de connexion et de connexion du proxy de services Web utilisé conjointement avec le connecteur cloud SANtricity sont entrées via la page saisir l'URL et les informations d'identification du proxy de services Web.

Vérifiez que vous avez bien établi une connexion au proxy de services Web SANtricity.

.Étapes
. Dans le champ *URL*, entrez l'URL du proxy de services Web utilisé pour SANtricity Cloud Connector.
. Dans le champ *Nom d'utilisateur*, entrez le nom d'utilisateur de la connexion Web Services Proxy.
. Dans le champ *Mot de passe*, entrez le mot de passe de la connexion Web Services Proxy.
. Cliquez sur *Tester la connexion* pour vérifier la connexion pour les informations d'identification proxy de services Web saisies.
. Après avoir vérifié les informations d'identification du proxy de services Web entrées via la connexion de test.
. Cliquez sur *Suivant*
+
Les informations d'identification proxy de services Web pour SANtricity Cloud Connector sont acceptées et la page Sélectionner les matrices de stockage s'affiche dans l'assistant de configuration.





=== Étape 5 : sélectionner les matrices de stockage

En fonction des informations d'identification du proxy de services Web SANtricity saisies dans l'assistant de configuration, une liste des matrices de stockage disponibles s'affiche sous la page Sélectionner des matrices de stockage. Cette page vous permet de sélectionner les baies de stockage utilisées par SANtricity Cloud Connector pour les tâches de sauvegarde et de restauration.

Assurez-vous que les matrices de stockage sont configurées pour votre application proxy de services Web SANtricity.


NOTE: Les baies de stockage inaccessibles observées par l'application SANtricity Cloud Connector entraînent des exceptions d'API dans le fichier journal. Il s'agit du comportement intentionnel de l'application SANtricity Cloud Connector lorsqu'une liste de volumes est extraite d'une baie inaccessible. Pour éviter ces exceptions d'API dans le fichier journal, vous pouvez résoudre le problème racine directement avec la matrice de stockage ou supprimer la matrice de stockage concernée de l'application proxy de services Web SANtricity.

.Étapes
. Cochez chaque case en regard de la baie de stockage que vous souhaitez attribuer à l'application SANtricity Cloud Connector pour les opérations de sauvegarde et de restauration.
. Cliquez sur *Suivant*.
+
Les matrices de stockage sélectionnées sont acceptées et la page Sélectionner les hôtes s'affiche dans l'assistant de configuration.

+

NOTE: Vous devez configurer un mot de passe valide pour toute matrice de stockage sélectionnée sur la page Sélectionner des matrices de stockage. Vous pouvez configurer les mots de passe de la matrice de stockage via la documentation de l'API proxy de services Web de SANtricity.





=== Étape 6 : sélectionner les hôtes

En fonction des baies de stockage hébergées par proxy de services Web sélectionnées via l'assistant de configuration, vous pouvez sélectionner un hôte disponible pour mapper les volumes de sauvegarde et de restauration des candidats vers l'application SANtricity Cloud Connector via la page Sélectionner les hôtes.

Vérifiez que vous disposez d'un hôte disponible via le proxy de services Web SANtricity.

.Étapes
. Dans le menu déroulant de la matrice de stockage répertoriée, sélectionnez l'hôte souhaité.
. Répétez l'étape 1 pour toutes les matrices de stockage supplémentaires répertoriées sous la page Sélectionner un hôte.
. Cliquez sur *Suivant*.
+
L'hôte sélectionné pour SANtricity Cloud Connector est accepté et la page de révision s'affiche dans l'assistant de configuration.





=== Étape 7 : examiner la configuration initiale

La page finale de l'assistant de configuration SANtricity Cloud Connector fournit un récapitulatif des résultats que vous avez saisis.

Examinez les résultats des données de configuration validées.

* Si toutes les données de configuration sont validées et établies avec succès, cliquez sur *Finish* pour terminer le processus de configuration.
* Si une section des données de configuration ne peut pas être validée, cliquez sur *Retour* pour accéder à la page applicable de l'assistant de configuration afin de réviser les données soumises.

