---
permalink: config-linux/fc-determine-host-port-wwpns-task.html 
sidebar: sidebar 
keywords: host wwpn, HBA utility, express linux configuration, software configuration, linux host, 
summary: 'Vous installez un utilitaire HBA FC afin de voir le nom international du port \(WWPN\) de chaque port hôte. De plus, vous pouvez utiliser l"utilitaire HBA pour modifier les paramètres recommandés dans la colonne Notes de l"outil NetApp Interoperability Matrix Tool pour la configuration prise en charge.' 
---
= Détermination des WWPN (Host Worldwide Port Name) dans les systèmes E-Series - Linux (FC)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous installez un utilitaire HBA FC, ce qui vous permet d'afficher le nom international du port (WWPN) de chaque port hôte.

En outre, vous pouvez utiliser l'utilitaire HBA pour modifier les paramètres recommandés dans la colonne Notes de l' https://mysupport.netapp.com/matrix["Matrice d'interopérabilité NetApp"^] pour la configuration prise en charge.

.Description de la tâche
Consultez les instructions suivantes pour les utilitaires HBA :

* La plupart des fournisseurs HBA proposent un utilitaire HBA. Vous aurez besoin de la version appropriée de HBA pour votre système d'exploitation hôte et votre processeur. Voici des exemples d'utilitaires FC HBA :
+
** Emulex OneCommand Manager pour les HBA Emulex
** QConverge Console de QLogic pour les HBA QLogic




.Étapes
. Téléchargez l'utilitaire approprié à partir du site Web du fournisseur de votre carte HBA.
. Installez l'utilitaire.
. Sélectionnez les paramètres appropriés dans l'utilitaire HBA.
+
Les paramètres appropriés pour votre configuration sont répertoriés dans la colonne Notes de l' https://mysupport.netapp.com/matrix["Matrice d'interopérabilité NetApp"^].


