---
permalink: config-linux/iscsi-configure-host-side-network-task.html 
sidebar: sidebar 
keywords: configure iSCSI networking, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Configurez la mise en réseau iSCSI côté hôte. 
---
= Configuration de la mise en réseau côté hôte dans E-Series - Linux (iSCSI)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour configurer la mise en réseau côté hôte, vous devez effectuer plusieurs étapes.

.Description de la tâche
Vous configurez la mise en réseau iSCSI côté hôte en définissant le nombre de sessions de nœud par chemin physique, en activant les services iSCSI appropriés, en configurant le réseau pour les ports iSCSI, en créant des liaisons de face iSCSI et en établissant des sessions iSCSI entre les initiateurs et les cibles.

Dans la plupart des cas, vous pouvez utiliser l'initiateur logiciel de la boîte de réception pour iSCSI CNA/NIC. Il n'est pas nécessaire de télécharger la dernière version du pilote, du micrologiciel et du BIOS. Reportez-vous à la https://mysupport.netapp.com/matrix["Matrice d'interopérabilité NetApp"^] pour déterminer les exigences en matière de code.

.Étapes
. Vérifier le `node.session.nr_sessions` variable du fichier /etc/iscsi/iscsid.conf pour afficher le nombre par défaut de sessions par chemin physique. Si nécessaire, remplacez le nombre de sessions par défaut par une session.
+
[listing]
----
node.session.nr_sessions = 1
----
. Modifiez le `node.session.timeo.replacement_timeout` variable du fichier /etc/iscsi/iscsid.conf vers `20`, à partir d'une valeur par défaut de `120`.
+
[listing]
----
node.session.timeo.replacement_timeout = 20
----
. Vous pouvez également définir `node.startup = automatic` dans /etc/iscsi/iscsid.conf avant d'exécuter toute `iscsiadm` les commandes pour que les sessions persistent après le redémarrage.
. Bien sûr `iscsid` et `(open-)iscsi` les services sont activés et activés pour le démarrage.
+
[listing]
----
# systemctl start iscsi
# systemctl start iscsid
# systemctl enable iscsi
# systemctl enable iscsid
----
. Obtenir le nom de l'initiateur IQN de l'hôte, qui sera utilisé pour configurer l'hôte sur une matrice.
+
[listing]
----
# cat /etc/iscsi/initiatorname.iscsi
----
. Configurez le réseau pour les ports iSCSI. Voici des exemples d'instructions pour RHEL et SLES :
+

NOTE: En plus du port de réseau public, les initiateurs iSCSI doivent utiliser au moins deux cartes réseau sur des segments privés ou des VLAN distincts.

+
.. Déterminez les noms des ports iSCSI à l'aide du `ifconfig -a` commande.
.. Définissez l'adresse IP des ports d'initiateur iSCSI. Les ports d'initiateur doivent être présents sur le même sous-réseau que les ports cibles iSCSI.
+
*Red Hat Enterprise Linux 8 (RHEL 8)*

+
Créez le fichier exemple `/etc/sysconfig/network-scripts/ifcfg-<NIC port>` avec les contenus suivants.

+
[listing]
----
TYPE=Ethernet
PROXY_METHOD=none
BROWSER_ONLY=no
BOOTPROTO=static
DEFROUTE=yes
IPV4_FAILURE_FATAL=no
NAME=<NIC port>
UUID=<unique UUID>
DEVICE=<NIC port>
ONBOOT=yes
IPADDR=192.168.xxx.xxx
PREFIX=24
NETMASK=255.255.255.0
NM_CONTROLLED=no
MTU=
----
+
Ajouts facultatifs concernant IPv6 :

+
[listing]
----
IPV6INIT=yes
IPV6_AUTOCONF=no
IPV6ADDR=fdxx::192:168:xxxx:xxxx/32
IPV6_DEFROUTE=yes
IPV6_FAILURE_FATAL=no
IPV6_ADDR_GEN_MODE=eui64
----
+
*Red Hat Enterprise Linux 9 (RHEL 9)*

+
Utilisez le `nmtui` outil permettant d'activer et de modifier une connexion. L'outil génère un `<NIC port>.nmconnection` fichier dans `/etc/NetworkManager/system-connections/`.

+
*SUSE Linux Enterprise Server 12 et 15 (SLES 12 et SLES 15)*

+
Créez le fichier exemple `/etc/sysconfig/network/ifcfg-<NIC port>` avec les contenus suivants.

+
[listing]
----
IPADDR='192.168.xxx.xxx/24'
BOOTPROTO='static'
STARTMODE='auto'
----
+
Ajout facultatif concernant IPv6 :

+
[listing]
----
IPADDR_0='fdxx::192:168:xxxx:xxxx/32'
----
+

NOTE: Veillez à définir l'adresse des deux ports d'initiateur iSCSI.

.. Redémarrez les services réseau.
+
[listing]
----
# systemctl restart network
----
.. Assurez-vous que le serveur Linux peut envoyer une commande ping _All_ des ports cibles iSCSI.


. Établissez les sessions iSCSI entre les initiateurs et les cibles (quatre au total) par l'une des deux méthodes suivantes.
+
.. (Facultatif) lors de l'utilisation des interfaces, configurez les interfaces iSCSI en créant deux liaisons iSCSI iface.
+
[listing]
----
# iscsiadm -m iface -I iface0 -o new
# iscsiadm -m iface -I iface0 -o update -n iface.net_ifacename -v <NIC port1>
----
+
[listing]
----
# iscsiadm -m iface -I iface1 -o new
# iscsiadm -m iface -I iface1 -o update -n iface.net_ifacename -v <NIC port2>
----
+

NOTE: Pour lister les interfaces, utilisez `iscsiadm -m iface`.

.. Détection des cibles iSCSI Enregistrez l'IQN (il sera le même avec chaque découverte) dans la feuille de travail pour l'étape suivante.
+
*Méthode 1 (avec ifâces)*

+
[listing]
----
# iscsiadm -m discovery -t sendtargets -p <target_ip_address>:<target_tcp_listening_port> -I iface0
# iscsiadm -m discovery -t sendtargets -p 192.168.0.1:3260 -I iface0
----
+
*Méthode 2 (sans lacets)*

+
[listing]
----
# iscsiadm -m discovery -t sendtargets -p <target_ip_address>:<target_tcp_listening_port>
# iscsiadm -m discovery -t sendtargets -p 192.168.0.1:3260
----
+

NOTE: L'IQN ressemble aux éléments suivants :

+
[listing]
----
iqn.1992-01.com.netapp:2365.60080e50001bf1600000000531d7be3
----
.. Créez la connexion entre les initiateurs iSCSI et les cibles iSCSI.
+
*Méthode 1 (avec ifâces)*

+
[listing]
----
# iscsiadm -m node -T <target_iqn> -p <target_ip_address>:<target_tcp_listening_port> -I iface0 -l
# iscsiadm -m node -T iqn.1992-01.com.netapp:2365.60080e50001bf1600000000531d7be3 -p 192.168.0.1:3260 -I iface0 -l
----
+
*Méthode 2 (sans lacets)*

+
[listing]
----
# iscsiadm -m node -L all
----
.. Lister les sessions iSCSI établies sur l'hôte.
+
[listing]
----
# iscsiadm -m session
----



