---
permalink: config-linux/iser-ib-install-configure-host-utilities-task.html 
sidebar: sidebar 
keywords: Linux Unified Host Utilities, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: 'LInstall Linux Unified Host Utilities lors de l"utilisation de iser.' 
---
= Installer et configurer Linux Unified Host Utilities
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les outils Linux Unified Host Utilities vous aident à gérer le stockage NetApp, y compris les règles de basculement et les chemins physiques.

.Étapes
. Utilisez le https://mysupport.netapp.com/matrix["Matrice d'interopérabilité NetApp"^] Pour déterminer la version appropriée d'Unified Host Utilities à installer.
+
Les versions sont répertoriées dans une colonne de chaque configuration prise en charge.

. Téléchargez les utilitaires d'hôtes unifiés à partir de https://mysupport.netapp.com/site/["Support NetApp"^].
+

NOTE: Vous pouvez également utiliser l'utilitaire SMDevices de SANtricity pour exécuter les mêmes fonctions que l'utilitaire hôte unifié. L'utilitaire SMDevices est inclus dans le package SMutils. Le package SMutils est un ensemble d'utilitaires qui permettent de vérifier ce que l'hôte voit de la matrice de stockage. Il est inclus dans l'installation du logiciel SANtricity.


