---
permalink: config-linux/nvme-roce-create-filesystems-sles-15-task.html 
sidebar: sidebar 
keywords: file systems, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Pour RHEL 9, RHEL 10, SLES 15 et SLES 16, vous créez un système de fichiers sur le périphérique nvme natif et montez le système de fichiers. 
---
= Créer des systèmes de fichiers dans E-Series - Linux (NVMe over RoCE)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour RHEL 9, RHEL 10, SLES 15 et SLES 16, vous créez un système de fichiers sur le périphérique nvme natif et montez le système de fichiers.

.Avant de commencer
Assurez-vous d'avoir terminé la link:nvme-roce-access-physical-targets-concept.html["accès aux volumes NVMe d'une cible E-Series depuis l'hôte"] tâche afin de garantir que les périphériques NVMe sont correctement configurés et accessibles.

.Étapes
. Créez un système de fichiers sur la partition du périphérique nvme souhaité à l'aide de l'emplacement `/dev/disk/by-id/nvme-eui.[id#]`.
+
La méthode de création d'un système de fichiers varie en fonction du système de fichiers choisi. Cet exemple illustre la création d'un `ext4` système de fichiers.

+
[listing]
----
# mkfs.ext4 /dev/disk/by-id/nvme-eui.000082dd5c05d39300a0980000a52225
mke2fs 1.42.11 (22-Oct-2019)
Creating filesystem with 2620928 4k blocks and 655360 inodes
Filesystem UUID: 97f987e9-47b8-47f7-b434-bf3ebbe826d0
Superblock backups stored on blocks:
        32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632

Allocating group tables: done
Writing inode tables: done
Creating journal (32768 blocks): done
Writing superblocks and filesystem accounting information: done
----
. Créez un dossier pour monter le nouveau périphérique.
+
[listing]
----
# mkdir /mnt/ext4
----
. Montez l'appareil.
+
[listing]
----
# mount /dev/disk/by-id/nvme-eui.000082dd5c05d39300a0980000a52225 /mnt/ext4
----


.Et la suite ?
Après avoir créé les systèmes de fichiers, link:nvme-roce-worksheet-for-concept.html["Enregistrez les informations de configuration de votre NVMr sur RoCE"].
