---
permalink: config-linux/nvme-ib-discover-connect-storage-host-task.html 
sidebar: sidebar 
keywords: discover storage, host, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: 'Avant de définir chaque hôte dans SANtricity System Manager, vous devez détecter les ports de contrôleur cible depuis l"hôte, puis établir les connexions NVMe.' 
---
= Découverte et connexion au stockage depuis l'hôte
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de définir chaque hôte dans SANtricity System Manager, vous devez détecter les ports de contrôleur cible depuis l'hôte, puis établir les connexions NVMe.

.Étapes
. Découvrez les sous-systèmes disponibles sur la cible NVMe-of pour tous les chemins à l'aide de la commande suivante :
+
[listing]
----
nvme discover -t rdma -a target_ip_address
----
+
Dans cette commande, `target_ip_address` Est l'adresse IP du port cible.

+

NOTE: Le `nvme discover` la commande détecte tous les ports du contrôleur dans le sous-système, quel que soit l'accès hôte.

+
[listing]
----
# nvme discover -t rdma -a 10.10.10.200
 Discovery Log Number of Records 2, Generation counter 0
 =====Discovery Log Entry 0======
 trtype:  rdma
 adrfam:  ipv4
 subtype: nvme subsystem
 treq:    not specified
 portid:  0
 trsvcid: 4420
 subnqn:  nqn.1992-08.com.netapp:5700.600a098000af41580000000058ed54be
 traddr: 10.10.10.200
 rdma_prtype: infiniband
 rdma_qptype: connected
 rdma_cms:    rdma-cm
 rdma_pkey: 0x0000
=====Discovery Log Entry 1======
 trtype:  rdma
 adrfam:  ipv4
 subtype: nvme subsystem
 treq:    not specified
 portid:  1
 trsvcid: 4420
 subnqn:  nqn.1992-08.com.netapp:5700.600a098000af41580000000058ed54be
 traddr: 11.11.11.100
 rdma_prtype: infiniband
 rdma_qptype: connected
 rdma_cms:    rdma-cm
 rdma_pkey: 0x0000
----
. Répétez l'étape 1 pour toutes les autres connexions.
. Connectez-vous au sous-système découvert sur le premier chemin à l'aide de la commande : `nvme connect -t rdma -n discovered_sub_nqn -a target_ip_address -Q queue_depth_setting -l controller_loss_timeout_period`
+

NOTE: La commande ci-dessus ne persiste pas lors du redémarrage. Le `nvme connect` L'exécution de la commande doit s'effectuer après chaque redémarrage pour rétablir les connexions NVMe.

+

NOTE: Les connexions NVMe ne persistent pas lors du redémarrage du système ou lorsque le contrôleur est indisponible pendant de longues périodes.

+

NOTE: Les connexions ne sont pas établies pour les ports découverts inaccessibles par l'hôte.

+

NOTE: Si vous spécifiez un numéro de port à l'aide de cette commande, la connexion échoue. Le port par défaut est le seul port configuré pour les connexions.

+

NOTE: Le paramètre de profondeur de file d'attente recommandé est 1024. Remplacer le paramètre par défaut 128 par 1024 à l'aide de ``-Q 1024``option de ligne de commande, comme indiqué dans l'exemple suivant.

+

NOTE: Le délai de perte de contrôleur recommandé en secondes est de 60 minutes (3600 secondes). Remplacer le réglage par défaut de 600 secondes avec 3600 secondes à l'aide de l' `-l 3600` option de ligne de commande, comme indiqué dans l'exemple suivant :

+
[listing]
----
# nvme connect -t rdma -a 10.10.10.200 -n nqn.1992-08.com.netapp:5700.600a098000af41580000000058ed54be -Q 1024 -l 3600
----
. Utilisez le `nvme list-subsys` Commande pour afficher la liste des périphériques NVMe actuellement connectés.
. Connectez-vous au sous-système découvert sur le second chemin :
+
[listing]
----
  # nvme connect -t rdma -a 11.11.11.100 -n nqn.1992-08.com.netapp:5700.600a098000af41580000000058ed54be -Q 1024 -l 3600
----
. Utilisez Linux `lsblk` et `grep` commandes permettant d'afficher des informations supplémentaires sur chaque périphérique de bloc :
+
[listing]
----
 # lsblk | grep nvme

 nvme0n1    259:0    0     5G  0 disk
 nvme1n1    259:0    0     5G  0 disk
----
. Utilisez le `nvme list` Commande pour afficher une nouvelle liste des périphériques NVMe actuellement connectés. Dans l'exemple ci-dessous, c'est le cas `nvme0n1` et `nvme0n1`.
+
[listing]
----
 # nvme list
 Node          SN            Model                   Namespace
 -------------------------------------------------------------
 /dev/nvme0n1  021648023161  NetApp E-Series          1
 /dev/nvme1n1  021648023161  NetApp E-Series          1
----
+
[listing]
----
Usage                 Format           FW Rev
--------------------------------------------------------------
5.37 GB /5.37 GB          512 B + 0 B      0842XXXX
5.37 GB /5.37 GB          512 B + 0 B      0842XXXX
----

