---
permalink: config-linux/nvme-roce-setup-failover-host-task.html 
sidebar: sidebar 
keywords: failover, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: 'Configurez l"hôte pour exécuter le basculement.' 
---
= Configuration du basculement sur l'hôte dans E-Series - Linux (NVMe over RoCE)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour fournir un chemin redondant à la matrice de stockage, vous pouvez configurer l'hôte pour qu'il exécute le basculement.

.Avant de commencer
Veuillez vous référer au  https://mysupport.netapp.com/matrix["Matrice d'interopérabilité NetApp"^] pour vous assurer que toutes les mises à jour requises sont installées, car des correctifs de bogues importants peuvent être nécessaires pour les versions de SLES ou RHEL qui ne sont pas disponibles dans la version initiale.

.Description de la tâche
Pour SLES 15, SLES 16, RHEL 9 et RHEL 10, le multipathing NVMe natif est activé par défaut et aucune configuration supplémentaire n'est requise.

.Et la suite ?
Avec le multipathing NVMe natif activé, link:nvme-roce-access-physical-targets-concept.html["accéder aux volumes NVMe d'une cible de la série E depuis l'hôte"].
