---
permalink: config-linux/nvme-roce-setup-failover-host-task.html 
sidebar: sidebar 
keywords: failover, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: 'Configurez l"hôte pour exécuter le basculement.' 
---
= Configuration du basculement sur l'hôte dans E-Series - Linux (NVMe over RoCE)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour fournir un chemin redondant à la matrice de stockage, vous pouvez configurer l'hôte pour qu'il exécute le basculement.

.Avant de commencer
Vous devez installer les modules requis sur votre système.

* Pour les hôtes Red Hat (RHEL), vérifiez que les packages sont installés en cours d'exécution `rpm -q device-mapper-multipath`
* Pour les hôtes SLES, vérifiez que les packages sont installés en cours d'exécution `rpm -q multipath-tools`



NOTE: Reportez-vous à la https://mysupport.netapp.com/matrix["Matrice d'interopérabilité NetApp"^] Pour s'assurer que les mises à jour requises sont installées, car les chemins d'accès multiples peuvent ne pas fonctionner correctement avec les versions GA de SLES ou de RHEL.

.Description de la tâche
SLES 12 utilise Device Mapper Multipath (DMMP) pour le multipathing pour NVMe sur RoCE. RHEL 8, RHEL 9, RHEL 10, SLES 15 et SLES 16 utilisent un basculement NVMe natif intégré. Selon le système d'exploitation que vous utilisez, une configuration supplémentaire du multipath est nécessaire pour assurer son bon fonctionnement.



== Activer les chemins d’accès multiples DMMP (Device Mapper) pour SLES 12

Par défaut, DM-MP est désactivé dans SLES. Procédez comme suit pour activer les composants DM-MP sur l’hôte.

.Étapes
. Ajoutez l'entrée du périphérique NVMe E-Series à la section Devices du `/etc/multipath.conf` comme indiqué dans l'exemple suivant :
+
[listing]
----

devices {
        device {
                vendor "NVME"
                product "NetApp E-Series*"
                path_grouping_policy group_by_prio
                failback immediate
                no_path_retry 30
        }
}
----
. Configurer `multipathd` pour démarrer au démarrage du système.
+
[listing]
----
# systemctl enable multipathd
----
. Démarrer `multipathd` s'il n'est pas en cours d'exécution.
+
[listing]
----
# systemctl start multipathd
----
. Vérifiez l'état de `multipathd` pour vérifier qu'il est actif et en cours d'exécution :
+
[listing]
----
# systemctl status multipathd
----




== Configuration de RHEL 8 avec des chemins d'accès multiples NVMe natifs

Les chemins d'accès multiples NVMe natifs sont désactivés par défaut dans RHEL 8 et doivent être activés via la procédure suivante.

. Configurez le  `modprobe` Règle d'activation des chemins d'accès multiples NVMe natifs.
+
[listing]
----
# echo "options nvme_core multipath=y" >> /etc/modprobe.d/50-nvme_core.conf
----
. Refaites `initramfs` avec les nouveaux `modprobe` paramètre.
+
[listing]
----
# dracut -f
----
. Redémarrez le serveur pour l'intégrer avec les chemins d'accès multiples NVMe natifs activés.
+
[listing]
----
# reboot
----
. Vérifiez que les chemins d'accès multiples NVMe natifs sont activés après le démarrage de l'hôte.
+
[listing]
----
# cat /sys/module/nvme_core/parameters/multipath
----
+
.. Si le résultat de la commande est `N`, Les chemins d'accès multiples NVMe natifs sont toujours désactivés.
.. Si le résultat de la commande est `Y`, Les chemins d'accès multiples NVMe natifs sont activés et les périphériques NVMe que vous découvrez utiliseront.





NOTE: Pour SLES 15, SLES 16, RHEL 9 et RHEL 10, le multipathing NVMe natif est activé par défaut et aucune configuration supplémentaire n'est requise.
