---
permalink: config-linux/nvme-fc-create-filesystems-sles-15-task.html 
sidebar: sidebar 
keywords: file systems, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Pour RHEL 8 et SLES 15, vous créez un système de fichiers sur le périphérique nvme natif et montez le système de fichiers. 
---
= Création de systèmes de fichiers dans la série E - Linux RHEL 8, RHEL 9, RHEL 10, SLES 15 et SLES 16 (NVMe sur FC)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour RHEL 8, RHEL 9, RHEL 10, SLES 15 et SLES 16, vous créez un système de fichiers sur le périphérique nvme natif et vous montez le système de fichiers.

.Étapes
. Exécutez la commande multipath -ll pour obtenir la liste des périphériques nvme.
+
[listing]
----
# multipath -ll
----
+
Le résultat de cette commande peut être utilisé pour rechercher les périphériques associés `/dev/disk/by-id/nvme-eui.[uuid#]` emplacement. Dans l'exemple ci-dessous, il s'agit de `/dev/disc/by-id/nvme-eui.000082dd5c05d39300a0980000a52225`.

+
[listing]
----
eui.000082dd5c05d39300a0980000a52225 [nvme]:nvme0n6 NVMe,NetApp E-Series,08520000
size=4194304 features='n/a' hwhandler='ANA' wp=rw
|-+- policy='n/a' prio=50 status=optimized
| `- 0:0:1 nvme0c0n1 0:0 n/a optimized     live
|-+- policy='n/a' prio=50 status=optimized
| `- 0:1:1 nvme0c1n1 0:0 n/a optimized     live
|-+- policy='n/a' prio=10 status=non-optimized
| `- 0:2:1 nvme0c2n1 0:0 n/a non-optimized live
`-+- policy='n/a' prio=10 status=non-optimized
  `- 0:3:1 nvme0c3n1 0:0 n/a non-optimized live
----
. Créez un système de fichiers sur la partition du périphérique nvme souhaité à l'aide de l'emplacement `/dev/disk/by-id/nvme-eui.[id#]`.
+
La méthode de création d'un système de fichiers varie en fonction du système de fichiers choisi. Cet exemple illustre la création d'un système de fichiers ext4.

+
[listing]
----
# mkfs.ext4 /dev/disk/by-id/nvme-eui.000082dd5c05d39300a0980000a52225
mke2fs 1.42.11 (22-Oct-2019)
Creating filesystem with 2620928 4k blocks and 655360 inodes
Filesystem UUID: 97f987e9-47b8-47f7-b434-bf3ebbe826d0
Superblock backups stored on blocks:
        32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632

Allocating group tables: done
Writing inode tables: done
Creating journal (32768 blocks): done
Writing superblocks and filesystem accounting information: done
----
. Créez un dossier pour monter le nouveau périphérique.
+
[listing]
----
# mkdir /mnt/ext4
----
. Montez l'appareil.
+
[listing]
----
# mount /dev/disk/by-id/nvme-eui.000082dd5c05d39300a0980000a52225 /mnt/ext4
----

