---
permalink: config-linux/nvme-ib-set-up-failover-task.html 
sidebar: sidebar 
keywords: failover, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: 'Configurez l"hôte pour exécuter le basculement.' 
---
= Configurez le basculement sur un hôte Linux E-Series en utilisant NVMe over InfiniBand
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour fournir un chemin redondant à la matrice de stockage, vous pouvez configurer l'hôte pour qu'il exécute le basculement.

.Avant de commencer
Vous devez installer les modules requis sur votre système.

* Pour les hôtes Red Hat (RHEL), vérifiez que les packages sont installés en cours d'exécution `rpm -q device-mapper-multipath`
* Pour les hôtes SLES, vérifiez que les packages sont installés en cours d'exécution `rpm -q multipath-tools`
+

NOTE: Reportez-vous à la section  https://mysupport.netapp.com/matrix["Matrice d'interopérabilité NetApp"^] Pour s'assurer que les mises à jour requises sont installées car les chemins d'accès multiples peuvent ne pas fonctionner correctement avec les versions GA de SLES ou de RHEL.



 SLES 12 use Device Mapper Multipath (DMMP) for multipathing when using NVMe over Infiniband. RHEL 8, RHEL 9, RHEL 10, SLES 15 and SLES 16 use a built-in Native NVMe Failover. Depending on which OS you are running, some additional configuration of multipath is required to get it running properly.


[[enable-device-mapper-multipath-dmmp-sles-12]]
== Activer les chemins d’accès multiples DMMP (Device Mapper) SLES 12

Par défaut, DM-MP est désactivé dans SLES. Procédez comme suit pour activer les composants DM-MP sur l’hôte.

.Étapes
. Ajoutez l'entrée de périphérique NVMe E-Series à la section périphériques du fichier /etc/multipath.conf, comme indiqué dans l'exemple suivant :
+
[listing]
----

devices {
        device {
                vendor "NVME"
                product "NetApp E-Series*"
                path_grouping_policy group_by_prio
                failback immediate
                no_path_retry 30
        }
}
----
. Configurer `multipathd` pour démarrer au démarrage du système.
+
[listing]
----
# systemctl enable multipathd
----
. Démarrer `multipathd` s'il n'est pas en cours d'exécution.
+
[listing]
----
# systemctl start multipathd
----
. Vérifiez l'état de `multipathd` pour vérifier qu'il est actif et en cours d'exécution :
+
[listing]
----
# systemctl status multipathd
----




[[setting-up-rhel-8-with-native-nvme-multipathing]]
== Configuration de RHEL 8 avec des chemins d'accès multiples NVMe natifs

Les chemins d'accès multiples NVMe natifs sont désactivés par défaut dans RHEL 8 et doivent être activés selon les étapes ci-dessous.

. Configuration `modprobe` Règle d'activation des chemins d'accès multiples NVMe natifs.
+
[listing]
----
# echo "options nvme_core multipath=y" >> /etc/modprobe.d/50-nvme_core.conf
----
. Refaites `initramfs` avec nouveau `modprobe` paramètre.
+
[listing]
----
# dracut -f
----
. Redémarrez le serveur pour l'intégrer avec les chemins d'accès multiples NVMe natifs activés.
+
[listing]
----
# reboot
----
. Vérifiez que les chemins d'accès multiples NVMe natifs ont été activés après le démarrage de l'hôte.
+
[listing]
----
# cat /sys/module/nvme_core/parameters/multipath
----
+
.. Si le résultat de la commande est `N`, Les chemins d'accès multiples NVMe natifs sont toujours désactivés.
.. Si le résultat de la commande est `Y`, Les chemins d'accès multiples NVMe natifs sont activés et les périphériques NVMe que vous découvrez utiliseront.





NOTE: Pour SLES 15 et RHEL 9, le multipathing NVMe natif est activé par défaut et aucune configuration supplémentaire n'est requise.



[[configure-nvme-io-policy]]
== Configurer la stratégie d'E/S NVMe

.Description de la tâche
Le multipathing natif NVMe sous Linux peut par défaut utiliser la politique d’E/S  `numa`. Pour les configurations NVMe-over-Fabrics des E-Series/EF-Series, la politique d’E/S recommandée est  `round-robin`, ce qui répartit les E/S de manière uniforme sur tous les chemins disponibles.

.Étapes
. Vérifiez la politique d'E/S NVMe actuelle :
+
[listing]
----
# cat /sys/module/nvme_core/parameters/iopolicy
numa
----
. Définissez la  `round-robin` stratégie d'E/S en utilisant l'une des méthodes suivantes :
+
** *Persistant (recommandé)* — Créez un fichier de règles udev :
+
.<code>/etc/udev/rules.d/71-nvme-io-policy.rules</code>
[listing]
----
ACTION=="add|change", SUBSYSTEM=="nvme-subsystem", ATTR{iopolicy}="round-robin"
----
+
Rechargez ensuite et appliquez les règles :

+
[listing]
----
udevadm control --reload
udevadm trigger --subsystem-match=nvme-subsystem
----
** *Paramètre global au démarrage* — Ajoutez le paramètre de noyau suivant à la configuration de votre chargeur de démarrage :
+
[listing]
----
nvme_core.iopolicy=round-robin
----
** *Non-persistant (en ligne, sans interruption d'E/S)* — Appliquez immédiatement sans redémarrer :
+
[listing]
----
echo "round-robin" > /sys/class/nvme-subsystem/nvme-subsys0/iopolicy
----
+

NOTE: Ce paramètre n'est pas conservé après un redémarrage.




