---
permalink: config-linux/nvme-tcp-setup-host-side-task.html 
sidebar: sidebar 
keywords: express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: 'La configuration de l"initiateur NVMe dans un environnement TCP comprend l"installation et la configuration du paquet nvme-cli, la configuration des adresses IP de l"initiateur et la mise en place de la couche NVMe-oF sur l"hôte.' 
---
= Configurez l’initiateur NVMe over TCP sur un hôte Linux E-Series.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La configuration de l'initiateur NVMe dans un environnement TCP comprend l'installation et la configuration du paquet nvme-cli, la configuration des adresses IP de l'initiateur et la mise en place de la couche NVMe-oF sur l'hôte.

.Avant de commencer
Vous devez utiliser la dernière version compatible de RHEL 9, RHEL 10, SLES 15 ou SLES 16 service pack. Consultez la  https://mysupport.netapp.com/matrix["Matrice d'interopérabilité NetApp"^] pour obtenir la liste complète des dernières exigences.

.Étapes
. Si vous utilisez le pilote Ethernet intégré pour votre HCA, installez le  `nvme-cli` package comme suit :
+
*SLES 15 ou SLES 16*

+
[listing]
----

# zypper install nvme-cli
----
+
*RHEL 9 et RHEL 10*

+
[listing]
----

# yum install nvme-cli
----
+
Si vous utilisez une NVIDIA HCA et souhaitez utiliser le pilote DOCA externe, veuillez consulter la link:https://developer.nvidia.com/doca-downloads["Documentation NVIDIA"] pour obtenir des informations sur la manière de l’installer correctement dans cet environnement.

. Pour RHEL 9, installez les scripts réseau :
+
*RHEL 9*

+
[listing]
----
# yum install NetworkManager-initscripts-updown
----
+

NOTE: Les scripts réseau ne sont pas disponibles pour RHEL 10.

. Procurez-vous le NQN hôte, qui sera utilisé pour configurer l'hôte sur une matrice.
+
[listing]
----
# cat /etc/nvme/hostnqn
----
. Configurez des adresses IPv4 sur les ports Ethernet utilisés pour connecter NVMe over TCP. Pour chaque interface réseau, créez un script de configuration contenant les différentes variables pour cette interface.
+
Les variables utilisées à cette étape sont basées sur le matériel serveur et l'environnement réseau. Les variables incluent le `IPADDR` et `GATEWAY`. Voici des exemples d'instructions pour SLES et RHEL :

+
*SLES 15*

+
Créez le fichier d'exemple  `/etc/sysconfig/network/ifcfg-eth4` avec le contenu suivant.

+
[listing]
----
BOOTPROTO='static'
BROADCAST=
ETHTOOL_OPTIONS=
IPADDR='192.168.1.87/24'
GATEWAY='192.168.1.1'
MTU=9000
NAME='<adapter name>'
NETWORK=
REMOTE_IPADDR=
STARTMODE='auto'
----
+
Créez ensuite le fichier exemple `/etc/sysconfig/network/ifcfg-eth5`:

+
[listing]
----
BOOTPROTO='static'
BROADCAST=
ETHTOOL_OPTIONS=
IPADDR='192.168.2.87/24'
GATEWAY='192.168.2.1'
MTU=9000
NAME='<adapter name>'
NETWORK=
REMOTE_IPADDR=
STARTMODE='auto'
----
+
*RHEL 9, RHEL 10 ou SLES 16*

+
Utilisez le `nmtui` outil permettant d'activer et de modifier une connexion. Voici un exemple de fichier `/etc/NetworkManager/system-connections/eth4.nmconnection` l'outil génère :

+
[listing]
----

[connection]
id=eth4
uuid=<unique uuid>
type=ethernet
interface-name=eth4

[ethernet]
mtu=9000

[ipv4]
address1=192.168.1.87/24
method=manual

[ipv6]
addr-gen-mode=default
method=auto

[proxy]
----
+
Voici un exemple de fichier `/etc/NetworkManager/system-connections/eth5.nmconnection` l'outil génère :

+
[listing]
----

[connection]
id=eth5
uuid=<unique uuid>
type=ethernet
interface-name=eth5

[ethernet]
mtu=9000

[ipv4]
address1=192.168.2.87/24
method=manual

[ipv6]
addr-gen-mode=default
method=auto

[proxy]
----
. Activez les interfaces réseau :
+
[listing]
----

# nmcli connection up eth4
# nmcli connection up eth5
----
. Configurez la couche NVMe-oF sur l'hôte. Créez le fichier suivant sous `/etc/modules-load.d/` pour charger le module noyau  `nvme_tcp` et assurez-vous que le module noyau restera toujours activé, même après un redémarrage :
+
[listing]
----

# cat /etc/modules-load.d/nvme_tcp.conf
  nvme_tcp
----
. Redémarrez l'hôte.
+
.. Vous pouvez également charger le  `nvme_tcp` module noyau sans redémarrer en exécutant cette commande :
+
[listing]
----

# modprobe nvme_tcp
----


. Vérifiez que le  `nvme_tcp` module noyau est chargé, exécutez cette commande :
+
[listing]
----
# lsmod | grep nvme
nvme_tcp               45056  0
nvme_fabrics           24576  1 nvme_tcp
nvme_core             114688  5 nvme_tcp,nvme_fabrics
t10_pi                 16384  2 sd_mod,nvme_core
----
+
.Et la suite ?
Après avoir configuré l’initiateur NVMe over TCP sur l’hôte, link:nvme-tcp-configure-storage-connections-task.html["configurer les paramètres du port NVMe over TCP"].


