---
permalink: config-linux/nvme-roce-define-host-task.html 
sidebar: sidebar 
keywords: define Linux host, configure linux host, express linux configuration, linux host, 
summary: 'SANtricity System Manager vous permet de définir les hôtes qui envoient des données à la baie de stockage. La définition d"un hôte est l"une des étapes requises pour permettre à la matrice de stockage de savoir quels hôtes lui sont connectés et d"autoriser l"accès E/S aux volumes.' 
---
= Création d'un hôte à l'aide de SANtricity System Manager - Linux (NVMe over RoCE)
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity System Manager vous permet de définir les hôtes qui envoient des données à la baie de stockage. La définition d'un hôte est l'une des étapes requises pour permettre à la matrice de stockage de savoir quels hôtes lui sont connectés et d'autoriser l'accès E/S aux volumes.

.Description de la tâche
Lorsque vous définissez un hôte, tenez compte des consignes suivantes :

* Vous devez définir les ports d'identificateur d'hôte associés à l'hôte.
* Assurez-vous de fournir le même nom que le nom de système attribué à l'hôte.
* Cette opération n'a pas de succès si le nom que vous choisissez est déjà utilisé.
* La longueur du nom ne doit pas dépasser 30 caractères.


.Étapes
. Sélectionnez menu:Storage[hosts].
. Cliquez sur menu:Créer [hôte].
+
La boîte de dialogue Créer un hôte s'affiche.

. Sélectionnez les paramètres de l'hôte, le cas échéant.
+
|===
| Réglage | Description 


 a| 
Nom
 a| 
Saisissez un nom pour le nouvel hôte.



 a| 
Type de système d'exploitation hôte
 a| 
Sélectionnez l'une des options suivantes dans la liste déroulante :

** * Linux* pour SANtricity 11.60 et versions ultérieures
** *Linux DM-MP (Kernel 3.10 ou version ultérieure)* pour la version pré-SANtricity 11.60




 a| 
Type d'interface hôte
 a| 
Sélectionnez le type d'interface hôte que vous souhaitez utiliser. Si la baie que vous configurez ne dispose que d'un seul type d'interface hôte, ce paramètre peut ne pas être disponible pour la sélection.



 a| 
Ports hôtes
 a| 
Effectuez l'une des opérations suivantes :

** *Sélectionnez interface d'E/S*
+
Si les ports hôtes sont connectés, vous pouvez sélectionner des identificateurs de port hôte dans la liste. Il s'agit de la méthode recommandée.

** *Ajout manuel*
+
Si les ports hôtes ne se sont pas connectés, consultez /etc/nvme/hostnqn sur l'hôte pour trouver les identificateurs hostnqn et les associer à la définition de l'hôte.

+
Vous pouvez entrer manuellement les identificateurs de port hôte ou les copier/coller à partir du fichier /etc/nvme/hostnqn (un par un) dans le champ *ports hôte*.

+
Vous devez ajouter un identificateur de port hôte à la fois pour l'associer à l'hôte, mais vous pouvez continuer à sélectionner autant d'identificateurs qui sont associés à l'hôte. Chaque identifiant est affiché dans le champ *ports hôte*. Si nécessaire, vous pouvez également supprimer un identificateur en sélectionnant *X* en regard de celui-ci.



|===
. Cliquez sur *Créer*.


.Résultat
Une fois l'hôte créé, SANtricity System Manager crée un nom par défaut pour chaque port hôte configuré pour l'hôte.

L'alias par défaut est ``<Hostname_Port Number>``. Par exemple, l'alias par défaut du premier port créé pour `host IPT is IPT_1`.
