---
permalink: config-linux/nvme-fc-setup-host-side-task.html 
sidebar: sidebar 
keywords: NVMe over Fibre Channel, host side, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: 'La configuration de l"initiateur NVMe dans un environnement Fibre Channel inclut l"installation et la configuration du pack nvme-cli, ainsi que l"activation de l"initiateur NVMe/FC sur l"hôte.' 
---
= Configurez l'initiateur NVMe over FC sur l'hôte dans E-Series - Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La configuration de l'initiateur NVMe dans un environnement Fibre Channel inclut l'installation et la configuration du pack nvme-cli, ainsi que l'activation de l'initiateur NVMe/FC sur l'hôte.

.Description de la tâche
La procédure suivante s’applique à RHEL 8, RHEL 9, SLES 12 et SLES 15 à l’aide d’adaptateurs HBA FC compatibles NVMe/FC Broadcom Emulex ou QLogic. Pour plus d’informations sur les versions de ces systèmes d’exploitation ou HBA prises en charge, consultez le https://mysupport.netapp.com/matrix["Matrice d'interopérabilité NetApp"^].

.Étapes
. Installer le `nvme-cli` groupe :
+
*SLES 12 ou SLES 15*

+
[listing]
----

# zypper install nvme-cli
----
+
*RHEL 8 ou RHEL 9*

+
[listing]
----

# yum install nvme-cli
----
+
.. Pour Qlogic, modifiez `/lib/systemd/system/nvmefc-boot-connections.service` Après avoir installé le script de connexion automatique NVMe/FC de Broadcom, vous pouvez :
+
[listing]
----
[Unit]
Description=Auto-connect to subsystems on FC-NVME devices found during boot

[Service]
Type=oneshot
ExecStart=/bin/sh -c "echo add > /sys/class/fc/fc_udev_device/nvme_discovery"

[Install]
WantedBy=default.target
----


. Activez et démarrez le `nvmefc-boot-connections` services.
+
[listing]
----
systemctl enable nvmefc-boot-connections.service
----
+
[listing]
----
systemctl start nvmefc-boot-connections.service
----


*Configuration côté hôte pour les HBA Emulex :*


NOTE: Les étapes suivantes concernent uniquement les HBA Emulex.

. Réglez `lpfc_enable_fc4_type` à `3` Pour activer SLES12 SP4 en tant qu'initiateur NVMe/FC.
+
[listing]
----
# cat /etc/modprobe.d/lpfc.conf
options lpfc lpfc_enable_fc4_type=3
----
. Recréez le `initrd` Pour obtenir la modification Emulex et le changement de paramètre de démarrage.
+
[listing]
----
# dracut --force
----
. Redémarrez l'hôte pour charger les modifications apportées à `Ipfc` conducteur.
+
[listing]
----
# reboot
----
+
L'hôte est redémarré et l'initiateur NVMe/FC est activé sur l'hôte.

+

NOTE: Une fois la configuration côté hôte terminée, la connexion des ports NVMe over Fibre Channel s'effectue automatiquement.


