---
permalink: config-linux/nvme-tcp-configure-storage-connections-task.html 
sidebar: sidebar 
keywords: NVMe over TCP, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Si votre contrôleur inclut une connexion pour NVMe over TCP, vous pouvez configurer les paramètres du port NVMe depuis la page Matériel ou la page Système dans SANtricity System Manager. 
---
= Configurer les connexions NVMe over TCP du système de stockage E-Series pour les hôtes Linux
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si votre contrôleur inclut une connexion pour NVMe over TCP, vous pouvez configurer les paramètres du port NVMe depuis la page Matériel ou la page Système dans SANtricity System Manager.

.Avant de commencer
Assurez-vous de disposer des éléments suivants :

* Un port hôte NVMe over TCP sur votre contrôleur ; sinon, les paramètres NVMe over TCP ne sont pas disponibles dans System Manager.
* Adresse IP de la connexion hôte.


.Description de la tâche
Vous pouvez accéder à la configuration NVMe over TCP depuis la page *Hardware* ou depuis le menu : Settings[System]. Cette tâche décrit comment configurer les ports depuis la page Hardware.


NOTE: Les paramètres et fonctions NVMe over TCP n'apparaissent que si le contrôleur de votre baie de stockage inclut un port NVMe over TCP.

.Étapes
. Dans le panneau de gauche de l'interface du System Manager, sélectionnez *Hardware*.
. Cliquez sur le contrôleur comportant le port NVMe over TCP que vous souhaitez configurer.
+
Le menu contextuel du contrôleur s'affiche.

. Sélectionnez *Configurer les ports NVMe over TCP*.
+
La boîte de dialogue *Configurer les ports NVMe over TCP* s'ouvre.

. Dans la liste déroulante, sélectionnez le port à configurer, puis cliquez sur *Suivant*.
. Sélectionnez les paramètres de configuration du port que vous souhaitez utiliser, puis cliquez sur *Suivant*.
+
Pour afficher tous les paramètres de port, cliquez sur le lien *Afficher plus de paramètres de port* à droite de la boîte de dialogue.

+
|===
| Paramètre de port | Description 


 a| 
Vitesse du port ethernet configurée
 a| 
Sélectionnez la vitesse souhaitée. Les options qui apparaissent dans la liste déroulante dépendent de la vitesse maximale que votre réseau peut prendre en charge (par exemple, 10 Gbit/s). Les valeurs possibles incluent :

** Négociation automatique
** 10 Gbits/s.
** 25 Gbits/s.
** 40 Gbits/s.
** 50 Gbits/s.
** 100 Gbits/s.
** 200 Gbits/s.



NOTE: La vitesse du port NVMe over TCP configurée doit correspondre à la capacité de vitesse du SFP sur le port sélectionné.



 a| 
Mode de correction d'erreurs directes (FEC) configuré
 a| 
Sélectionnez le mode FEC souhaité. Les options qui apparaissent dans la liste déroulante dépendent de la vitesse actuellement sélectionnée et ne répertorient que les options prises en charge avec cette vitesse. Tous les modes FEC ne sont pas disponibles pour toutes les vitesses. Les valeurs possibles incluent :

** Aucune
** Reed-Solomon
** Code de sécurité incendie
** Automatique




 a| 
Activez IPv4 et/ou IPv6
 a| 
Sélectionnez une ou les deux options pour activer la prise en charge des réseaux IPv4 et IPv6.



 a| 
Taille MTU (disponible en cliquant sur *Afficher plus de paramètres de port*).
 a| 
Si nécessaire, entrez une nouvelle taille en octets pour l'unité de transmission maximale (MTU). La taille de MTU par défaut est de 1500 octets par trame. Vous devez entrer une valeur comprise entre 1500 et 9000.

|===
+
Si vous avez sélectionné *Activer IPv4*, une boîte de dialogue s'ouvre pour sélectionner les paramètres IPv4 après avoir cliqué sur *Suivant*. Si vous avez sélectionné *Activer IPv6*, une boîte de dialogue s'ouvre pour sélectionner les paramètres IPv6 après avoir cliqué sur *Suivant*. Si vous avez sélectionné les deux options, la boîte de dialogue des paramètres IPv4 s'ouvre en premier, puis après avoir cliqué sur *Suivant*, la boîte de dialogue des paramètres IPv6 s'ouvre.

. Configurez les paramètres IPv4 et/ou IPv6, automatiquement ou manuellement. Pour afficher tous les paramètres de port, cliquez sur le lien *Afficher plus de paramètres* à droite de la boîte de dialogue.
+
|===
| Paramètre de port | Description 


 a| 
Obtention automatique de la configuration auprès du serveur DHCP
 a| 
Sélectionnez cette option pour obtenir la configuration automatiquement.



 a| 
Spécifiez manuellement la configuration statique
 a| 
Sélectionnez cette option, puis entrez une adresse statique dans les champs. Pour IPv4, incluez le masque de sous-réseau réseau et la passerelle. Pour IPv6, incluez les adresses IP routables et l'adresse IP du routeur.


NOTE: S'il n'y a qu'une seule adresse IP routable, définissez l'adresse restante sur 0:0:0:0:0:0:0:0:0.



 a| 
Activez la prise en charge VLAN (disponible en cliquant sur *Afficher plus de paramètres*).
 a| 

NOTE: Cette option est uniquement disponible dans un environnement iSCSI. Elle n'est pas disponible dans un environnement NVMe over TCP.



 a| 
Activez la priorité ethernet (disponible en cliquant sur *Afficher plus de paramètres*).
 a| 

NOTE: Cette option est uniquement disponible dans un environnement iSCSI. Elle n'est pas disponible dans un environnement NVMe over TCP.

|===
. Cliquez sur *Terminer*.


.Et la suite ?
Après avoir configuré les paramètres du port NVMe sur TCP, link:nvme-tcp-discover-connect-storage-host-task.html["découvrir et connecter le stockage sur l'hôte"].
