---
permalink: config-linux/nvme-fc-setup-failover-host-task.html 
sidebar: sidebar 
keywords: failover, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: 'Configurez l"hôte pour exécuter le basculement.' 
---
= Configurez le basculement sur l'hôte
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour fournir un chemin redondant à la matrice de stockage, vous pouvez configurer l'hôte pour qu'il exécute le basculement.

.Avant de commencer
Vous devez installer les modules requis sur votre système.

* Pour les hôtes Red Hat (RHEL), vérifiez que les packages sont installés en cours d'exécution `rpm -q device-mapper-multipath`
* Pour les hôtes SLES, vérifiez que les packages sont installés en cours d'exécution `rpm -q multipath-tools`


.Description de la tâche
RHEL 7 et SLES 12 utilisent Device Mapper Multipath (DMMP) pour les chemins d'accès multiples lors de l'utilisation de NVMe sur Fibre Channel. RHEL 8, RHEL 9 et SLES 15 utilisent un basculement NVMe natif intégré. Selon le système d'exploitation que vous utilisez, une configuration supplémentaire de chemins d'accès multiples est requise pour assurer son bon fonctionnement.



== Activez Device Mapper Multipath (DMMP) pour RHEL 7 ou SLES 12

Par défaut, DM-MP est désactivé dans RHEL et SLES. Procédez comme suit pour activer les composants DM-MP sur l'hôte.

.Étapes
. Ajoutez l'entrée de périphérique NVMe E-Series à la section périphériques du fichier /etc/multipath.conf, comme indiqué dans l'exemple suivant :
+
[listing]
----

devices {
        device {
                vendor "NVME"
                product "NetApp E-Series*"
                path_grouping_policy group_by_prio
                failback immediate
                no_path_retry 30
        }
}
----
. Configurer `multipathd` pour démarrer au démarrage du système.
+
[listing]
----
# systemctl enable multipathd
----
. Démarrer `multipathd` s'il n'est pas en cours d'exécution.
+
[listing]
----
# systemctl start multipathd
----
. Vérifiez l'état de `multipathd` pour vérifier qu'il est actif et en cours d'exécution :
+
[listing]
----
# systemctl status multipathd
----




== Configuration des chemins d'accès multiples NVMe natifs pour RHEL 8

.Description de la tâche
Les chemins d'accès multiples NVMe natifs sont désactivés par défaut dans RHEL 8 et doivent être activés selon les étapes ci-dessous.

.Étapes
. Configuration `modprobe` Règle d'activation des chemins d'accès multiples NVMe natifs.
+
[listing]
----
# echo "options nvme_core multipath=y" >> /etc/modprobe.d/50-nvme_core.conf
----
. Refaites `initramfs` avec nouveau paramètre modprobe.
+
[listing]
----
# dracut -f
----
. Redémarrez le serveur pour l'intégrer avec les chemins d'accès multiples NVMe natifs activés
+
[listing]
----
# reboot
----
. Vérifiez que les chemins d'accès multiples NVMe natifs ont été activés après le démarrage de l'hôte.
+
[listing]
----
# cat /sys/module/nvme_core/parameters/multipath
----
+
.. Si le résultat de la commande est `N`, Les chemins d'accès multiples NVMe natifs sont toujours désactivés.
.. Si le résultat de la commande est `Y`, Les chemins d'accès multiples NVMe natifs sont activés et les périphériques NVMe que vous découvrez utiliseront.





NOTE: Pour RHEL 9 et SLES 15, les chemins d'accès multiples NVMe natifs sont activés par défaut et aucune configuration supplémentaire n'est requise.
