---
permalink: config-linux/sas-install-configure-host-utilities-task.html 
sidebar: sidebar 
keywords: Linux Unified Host Utilities, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries, SMcli, SMdevices 
summary: Linux Unified Host Utilities 7.1 comprend des outils destinés à la gestion du stockage NetApp, y compris les règles de basculement et les chemins physiques. 
---
= Installer et configurer les utilitaires d'hôtes unifiés Linux dans les baies E-Series (SAS)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les outils Linux Unified Host Utilities vous aident à gérer le stockage NetApp, y compris les règles de basculement et les chemins physiques.

.Étapes
. Utilisez le https://mysupport.netapp.com/matrix["Matrice d'interopérabilité NetApp"^] Pour déterminer la version appropriée d'Unified Host Utilities à installer.
+
Les versions sont répertoriées dans une colonne de chaque configuration prise en charge.

. Téléchargez les utilitaires d'hôtes unifiés à partir de https://mysupport.netapp.com/site/["Support NetApp"^].
+

NOTE: Vous pouvez également utiliser la commande SMcli `-identifyDevices` Pour exécuter les mêmes fonctions que l'outil Unified Host Utility. Le logiciel SMcli est inclus dans le système d'exploitation SANtricity et téléchargeable via SANtricity System Manager. Pour plus d'informations sur le téléchargement de SMcli via le Gestionnaire système SANtricity, reportez-vous au https://docs.netapp.com/us-en/e-series-santricity/sm-settings/download-cli.html["Téléchargez la rubrique de l'interface de ligne de commande dans l'aide en ligne de SANtricity System Manager"^].


