---
sidebar: sidebar 
permalink: manage-storage.html 
keywords: online help, System Manager, Unified Manager 
summary: Gérer le stockage 
---
= Gérez les systèmes de stockage E-Series
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Utilisez les liens ci-dessous pour accéder à une documentation décrivant la configuration, la gestion et la surveillance des objets de stockage et des systèmes de stockage E-Series. Les liens vous mènent à un autre site de documentation.



== Aide en ligne de System Manager

Accédez au https://docs.netapp.com/us-en/e-series-santricity/system-manager/index.html["Aide en ligne de SANtricity System Manager"^], où vous pouvez trouver des informations sur la planification, la configuration, la gestion et le dépannage de votre matrice de stockage.



== Aide en ligne d'Unified Manager

Accédez au https://docs.netapp.com/us-en/e-series-santricity/unified-manager/index.html["Aide en ligne de SANtricity Unified Manager"^], où vous pouvez apprendre à exécuter des commandes de gestion du stockage sur plusieurs matrices de stockage réseau.



== Référence de commande

Accédez au https://docs.netapp.com/us-en/e-series-cli/index.html["Référence de commande"^], Où vous pouvez apprendre à configurer et à surveiller vos matrices de stockage à l'aide des commandes de l'interface de ligne de commande (CLI).
