---
sidebar: sidebar 
permalink: manage-storage.html 
keywords: online help, System Manager, Unified Manager 
summary: Gérer le stockage 
---
= Gérer le stockage
:allow-uri-read: 


[role="lead"]
Utilisez les liens ci-dessous pour accéder à une documentation décrivant la configuration, la gestion et la surveillance des objets de stockage et des systèmes de stockage E-Series. Les liens vous mènent à un autre site de documentation.



== Aide en ligne de System Manager 11.7

Accédez au https://docs.netapp.com/us-en/e-series-santricity/system-manager/index.html["Aide en ligne de SANtricity System Manager 11.7"^], où vous pouvez trouver des informations sur la planification, la configuration, la gestion et le dépannage de votre matrice de stockage.



== Aide en ligne de Unified Manager 5

Accédez au https://docs.netapp.com/us-en/e-series-santricity/unified-manager/index.html["Aide en ligne de SANtricity Unified Manager 5"^], où vous pouvez apprendre à exécuter des commandes de gestion du stockage sur plusieurs baies de stockage réseau.



== Référence de commande

Accédez au https://docs.netapp.com/us-en/e-series-cli/index.html["Référence de commande"^], Où vous pouvez apprendre à configurer et à surveiller vos matrices de stockage à l'aide des commandes de l'interface de ligne de commande (CLI).
