---
sidebar: sidebar 
permalink: rackmount-hardware.html 
keywords: rackmount, rack-mount, install in rack, rails 
summary: 'Le matériel de montage en rack sert à installer votre matériel dans une baie ou une armoire. Les instructions d"installation doivent être incluses dans la boîte du matériel de montage en rack. Cependant, si vous avez besoin d"accéder aux instructions d"installation, utilisez le lien approprié ci-dessous.' 
---
= Matériel de montage en rack - E-Series
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Le matériel de montage en rack est utilisé pour installer votre système de stockage dans une baie ou une armoire. Les instructions d'installation doivent être incluses dans la boîte du matériel de montage en rack. Cependant, si vous avez besoin d'accéder aux instructions d'installation, utilisez le lien approprié ci-dessous.

Pour les systèmes de stockage plus récents, vous pouvez vérifier le matériel de montage en rack pris en charge en consultant le NetApp Hardware Universe à  https://hwu.netapp.com["NetApp Hardware Universe"^].



[[adjustable-support-rails]]
== Rails de support réglables

L'accès https://mysupport.netapp.com/ecm/ecm_download_file/ECMP1652045["Installation des rails de support réglables"^] pour installer un plateau de contrôleur ou un plateau de lecteur livré séparément (non déjà installé dans l'armoire). Cette procédure est applicable aux bacs 2U (9 cm ou 3.5 pouces) suivants :

* DE1600 ou DE5600
* E2612 ou E2624
* E5412, E5424, E5512 OU E5524




[[two-post-rack-2u]]
== Rack à deux montants -- 2U

L'accès https://mysupport.netapp.com/ecm/ecm_download_file/ECMM1280302["Installation d'un équipement 2U dans un rack à deux montants"^].



[[four-post-rack-or-cabinet-2u]]
== Rack ou armoire à quatre montants -- 2U

L'accès https://mysupport.netapp.com/ecm/ecm_download_file/ECMLP2484194["Installation d'un boîtier 2U de 12 disques dans un rack ou une armoire à quatre montants"^].



[[four-post-rack-superrail]]
== Rack à quatre montants -- SuperRail

Accéder https://docs.netapp.com/us-en/ontap-systems/platform-supplemental/superrail-install.html["Installer SuperRail dans un rack à quatre montants"^].
