---
sidebar: sidebar 
permalink: whats-new.html 
keywords: whats new, new features, SANtricity 11.73 
summary: Nouvelles fonctionnalités de SANtricity OS. 
---
= Nouveautés de SANtricity OS
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le tableau suivant décrit les nouvelles fonctionnalités de SANtricity OS 11.8 pour la gestion intégrée des contrôleurs EF300, EF600, E2800/EF280 et E5700/EF570.



== Nouvelles fonctionnalités de la version 11.80

[cols="35h,~"]
|===
| Nouvelle fonction | Description 


 a| 
Analyse améliorée de parité des volumes
 a| 
L'analyse de parité des volumes peut désormais être lancée en arrière-plan via l'API REST ou l'interface de ligne de commande. L'acquisition de parité résultante s'exécute en arrière-plan tant que l'opération d'acquisition est nécessaire. Les opérations d'analyse survivent aux redémarrages du contrôleur et aux opérations de basculement.



 a| 
Prise en charge de SAML pour Unified Manager
 a| 
Unified Manager prend désormais en charge le langage SAML (Security assertion Markup Language). Une fois SAML activé pour Unified Manager, les utilisateurs doivent utiliser l'authentification multifacteur contre le fournisseur d'identités pour interagir avec l'interface utilisateur. Notez qu'une fois SAML activé sur Unified Manager, l'API REST ne peut pas être utilisée sans passer par le fournisseur d'accès intégré pour authentifier les requêtes.



 a| 
Fonction de configuration automatique
 a| 
Prend désormais en charge la possibilité de définir le paramètre de taille de bloc de volume à utiliser avec la fonction de configuration automatique pour la configuration initiale de la baie. Cette fonction est disponible dans l'interface de ligne de commande uniquement en tant que paramètre « blockSize ».



 a| 
Signature cryptographique du micrologiciel du contrôleur
 a| 
Le firmware du contrôleur est signé cryptographiquement. Les signatures sont vérifiées lors du téléchargement initial et au démarrage de chaque contrôleur. Aucun impact attendu sur l'utilisateur final. Les signatures sont soutenues par un certificat de validation étendue émis par l'autorité de certification.



 a| 
Signature cryptographique du micrologiciel du lecteur
 a| 
Le firmware du disque est signé cryptographiquement. Les signatures sont vérifiées lors du téléchargement initial et sont soutenues par un certificat de validation étendue émis par l'autorité de certification. Le contenu du micrologiciel du lecteur est désormais livré sous forme de fichier ZIP, qui contient l'ancien micrologiciel non signé ainsi que le nouveau micrologiciel signé. L'utilisateur doit choisir le fichier approprié en fonction de la version de code exécutée sur le système cible.



 a| 
Gestion du serveur de clés externe - taille de la clé de certificat
 a| 
La nouvelle taille de clé de certificat par défaut est de 3072 bits (à partir de 2048). Les tailles de clé jusqu'à 4096 bits sont prises en charge. Un bit NVSRAM doit être modifié pour prendre en charge les tailles de clé autres que celles par défaut.

Les valeurs de sélection de taille de clé sont les suivantes :

* VALEUR PAR DÉFAUT = 0
* LONGUEUR 2048 = 1
* LONGUEUR 3072 = 2
* LONGUEUR 4096 = 3


Pour modifier la taille de la clé à 4096 via SMcli :

`set controller[b] globalnvsrambyte[0xc0]=3;`
`set controller[a] globalnvsrambyte[0xc0]=3;`

Interroger la taille de la clé :

`show allcontrollers globalnvsrambyte[0xc0];`



 a| 
Amélioration des pools de disques
 a| 
Les pools de disques créés avec des contrôleurs exécutant la version 11.80 ou supérieure seront des pools _version 1_ et non des pools _version 0_. Une opération de mise à niveau vers une version antérieure est limitée lorsqu'un pool de disques _version 1_ existe.

La version d'un pool de disques peut être identifiée dans le profil de la matrice de stockage.



 a| 
System Manager et Unified Manager ne se lancent que si la configuration minimale requise pour le navigateur est respectée
 a| 
Une version minimale de l'explorateur est requise avant le lancement de System Manager ou d'Unified Manager.

Les versions minimales prises en charge sont les suivantes :

* Firefox version minimale 80
* Chrome version minimale 89
* Edge version minimale 90
* Safari version minimale 14




 a| 
Prise en charge des disques SSD NVMe FIPS 140-3
 a| 
Les disques SSD NVMe FIPS 140-3 certifiés NetApp sont désormais pris en charge. Ils seront correctement identifiés en tant que tels dans le profil de la baie de stockage et dans System Manager.



 a| 
Prise en charge du cache de lecture SSD sur les systèmes EF300 et EF600
 a| 
Le cache de lecture SSD est désormais pris en charge sur les contrôleurs EF300 et EF600 utilisant des disques durs avec extension SAS.



 a| 
Prise en charge de la mise en miroir à distance asynchrone Fibre Channel et iSCSI sur les systèmes EF300 et EF600
 a| 
La mise en miroir à distance asynchrone (ARVM) est désormais prise en charge sur les contrôleurs EF300 et EF600 avec des volumes basés sur NVMe et SAS.



 a| 
Prise en charge des modèles EF300 et EF600 sans lecteur dans le bac de base
 a| 
Les configurations de contrôleurs EF300 et EF600 sans disques NVMe dans le bac de base sont désormais prises en charge.



 a| 
Ports USB désactivés pour toutes les plates-formes
 a| 
Les ports USB sont maintenant désactivés sur toutes les plates-formes.



 a| 
Cache de lecture SSD amélioré
 a| 
Cache de lecture SSD de 5 à 8 To maximum.



 a| 
Attribuez un cache de lecture 100 % Flash à un seul volume dans les configurations duplex
 a| 
Tous les cache de lecture SSD peuvent désormais être affectés au même volume sur les systèmes duplex lorsqu'un seul volume utilise l'intégralité du cache SSD.



 a| 
Numéro de série du lecteur ajouté au tableau récapitulatif du lecteur du profil de matrice de stockage
 a| 
Le numéro de série du lecteur a été ajouté au tableau récapitulatif du lecteur dans le profil Storage Array.



 a| 
Ajout de dom0-misc-logs à l'ASUP quotidien
 a| 
Les journaux dom0-misc pour les contrôleurs A et B ont été ajoutés aux ASUPs quotidiens.



 a| 
Le port 443 est maintenant utilisé par défaut pour les applications qui communiquent avec les services Web intégrés
 a| 
Le port 443 est maintenant utilisé par défaut lors de la communication avec le serveur Web intégré. Le  `-useLegacyTransferPort` La commande CLI a été ajoutée pour ceux qui souhaitent utiliser le port de transfert 8443 existant. Pour plus d'informations sur la nouvelle commande -useLegacyTransferPort CLI, reportez-vous au https://docs.netapp.com/us-en/e-series-cli/whats-new.html["Nouveautés de l'interface de ligne de commande SANtricity"].



 a| 
Capacité de progression de la parité du volume de numérisation
 a| 
Les commandes CLI suivantes ont été implémentées pour prendre en charge les opérations d'analyse de parité de volume basées sur des travaux :

* Commencez par vérifier la parité du volume
* Enregistrer les erreurs de la tâche de parité du volume de vérification
* Arrêter la vérification de la parité du volume
* Affiche le ou les travaux de vérification de parité de volume


Pour plus d'informations sur les nouvelles commandes CLI de l'analyse de parité de volume basée sur les tâches, reportez-vous au https://docs.netapp.com/us-en/e-series-cli/whats-new.html["Nouveautés de l'interface de ligne de commande SANtricity"].



 a| 
Prise en charge de MFA pour Unified Manager
 a| 
La prise en charge de l'authentification multifacteur (MFA) est désormais prise en charge dans Unified Manager.



 a| 
Icône de basculement pour la vue matérielle avant-arrière
 a| 
Dans la vue matériel de System Manager/Unified Manager, les deux onglets suivants sont désormais disponibles pour contrôler les vues avant et arrière :

* Onglet lecteurs
* Onglet contrôleurs et composants




 a| 
Plug-in vCenter Storage
 a| 
Le plug-in vCenter Storage a été mis à jour pour assurer la compatibilité avec la version E-Series 11.80.



 a| 
Proxy de services Web 6.0
 a| 
Le proxy de services Web a été mis à jour vers la version 6.0 pour assurer la compatibilité avec la version 11.80 du système E-Series.



 a| 
Suppression de l'indicateur de création de dossier ASUP pour les événements de température nominale et maximale dépassés de la gamme E-Series
 a| 
L'indicateur de création de cas est maintenant désactivé pour les événements de dépassement de température nominale et maximale ne nécessitant aucune action.



 a| 
Indicateur de création de cas prioritaire activé pour l'événement Mel 0x1209
 a| 
Un indicateur de création de cas est maintenant créé pour le `MEL_EV_DEGRADE_CHANNEL 0x1209` Événement MEL.

|===