---
permalink: config-vmware/discover-storage-host-task.html 
sidebar: sidebar 
keywords: discover storage ESXi, express vmware configuration, software configuration, vmware host, E2800, E5700, EF300, EF600, EF50, EF80, E4000, E-Series, eseries 
summary: 'Une fois les volumes affectés à l"hôte, vous effectuez une nouvelle analyse afin que l"hôte détecte et configure les volumes pour les chemins d"accès multiples.' 
---
= Découvrez le stockage sur l'hôte dans E-Series pour VMware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Attribuez les volumes à l'hôte. Effectuez une nouvelle analyse afin que l'hôte détecte et configure les volumes pour le multipathing.

Pour plus d'informations sur la création d'hôtes et l'attribution de volumes, consultez :

* https://docs.netapp.com/us-en/e-series-santricity/sm-storage/create-host-manually.html["Créer des définitions d'hôte"^]
* https://docs.netapp.com/us-en/e-series-santricity/sm-storage/create-host-cluster.html["Créer un cluster d'hôtes"^]
* https://docs.netapp.com/us-en/e-series-santricity/sm-storage/assign-volumes.html["Attribuer des volumes aux hôtes"^]


Par défaut, un hôte ESXi effectue automatiquement une nouvelle analyse toutes les cinq minutes. Un volume peut apparaître entre le moment de sa création et de son affectation à un hôte, avant d'effectuer une nouvelle analyse manuelle. Quoi qu'il en soit, vous pouvez effectuer une nouvelle analyse manuelle pour vous assurer que tous les volumes sont correctement configurés.

.Étapes
. Assurez-vous que les volumes sont créés et attribués à l'hôte ESXi comme décrit dans les liens ci-dessus.
. Si vous utilisez un serveur vCenter, ajoutez l'hôte à l'inventaire du serveur.
. Utilisez le client vSphere ou le client Web vSphere pour vous connecter directement à vCenter Server ou à l'hôte ESXi.
. Pour obtenir des instructions sur la manière d'effectuer une nouvelle analyse du stockage sur un hôte ESXi, consultez https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/9-1/vsphere-storage/managing-esxi-storage-devices/rescan-operations-for-esxi-storage/perform-storage-rescan.html["Effectuer une nouvelle analyse du stockage"^].

