---
permalink: config-vmware/discover-storage-host-task.html 
sidebar: sidebar 
keywords: discover storage ESXi, express vmware configuration, software configuration, vmware host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: 'Une fois les volumes affectés à l"hôte, vous effectuez une nouvelle analyse afin que l"hôte détecte et configure les volumes pour les chemins d"accès multiples.' 
---
= Découvrez le stockage sur l'hôte dans la gamme E-Series - VMware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Une fois les volumes affectés à l'hôte, vous effectuez une nouvelle analyse afin que l'hôte détecte et configure les volumes pour les chemins d'accès multiples.

Par défaut, un hôte ESXi effectue automatiquement une nouvelle analyse toutes les cinq minutes. Un volume peut apparaître entre le moment de sa création et de son affectation à un hôte, avant d'effectuer une nouvelle analyse manuelle. Quoi qu'il en soit, vous pouvez effectuer une nouvelle analyse manuelle pour vous assurer que tous les volumes sont correctement configurés.

.Étapes
. Créez un ou plusieurs volumes et affectez-les à l'hôte ESXi.
. Si vous utilisez un serveur vCenter, ajoutez l'hôte à l'inventaire du serveur.
. Utilisez le client vSphere ou le client Web vSphere pour vous connecter directement à vCenter Server ou à l'hôte ESXi.
. Pour obtenir des instructions sur la façon d'effectuer une nouvelle analyse du stockage sur un hôte ESXi, recherchez l' https://support.broadcom.com/["Base de connaissances VMware"^]article sur cette rubrique.

