---
sidebar: sidebar 
permalink: vcenter-plugin/san-spvc-ic-installation.html 
keywords: install vCenter plugin, installing vCenter plugin, vCenter plugin, 
summary: Installez ou mettez à niveau le plug-in de stockage SANtricity pour vCenter. 
---
= Installez ou mettez à niveau le plug-in de stockage pour vCenter
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Procédez comme suit pour installer le plug-in de stockage pour vCenter et vérifier l'enregistrement du plug-in. Vous pouvez également mettre à niveau le plug-in en suivant ces instructions.



== Passer en revue les conditions préalables à l'installation

Assurez-vous que vos systèmes répondent aux exigences de la section link:san-spvc-ic-reqs.html["Examinez les conditions d'installation et de mise à niveau"].


NOTE: Le processus de mise à niveau ne conserve pas les fichiers *vcenter.properties*. Si vous effectuez une mise à niveau, vous devez annuler l'enregistrement du plug-in avant la mise à niveau. Une fois la mise à niveau réussie, vous pouvez enregistrer à nouveau le plugin sur le vCSA.



== Installez le logiciel du plug-in

Pour installer le logiciel du plug-in :

. Copiez le fichier du programme d'installation sur l'hôte qui sera utilisé comme serveur d'applications, puis accédez au dossier où vous avez téléchargé le programme d'installation.
. Double-cliquez sur le fichier d'installation :
+
`santricity_storage_vcenterplugin-windows_x64-- nn.nn.nn.nnnn.exe`

+
Dans le nom de fichier ci-dessus, `nn.nn.nn.nnnn` représente le numéro de version.

. Lorsque l'installation démarre, suivez les invites à l'écran pour activer plusieurs fonctionnalités et saisir certains paramètres de configuration. Si nécessaire, vous pouvez modifier l'une de ces sélections ultérieurement dans les fichiers de configuration.
+

NOTE: Lors d'une mise à niveau, vous n'êtes pas invité à entrer les paramètres de configuration.

+

NOTE: Au cours de l'installation, vous êtes invité à valider votre certificat. Cochez cette case si vous souhaitez appliquer la validation de certificat entre le plug-in et les matrices de stockage. Avec cette mise en œuvre, les certificats de la matrice de stockage sont vérifiés pour être approuvés par rapport au plug-in. Si les certificats ne sont pas approuvés, ils ne sont pas autorisés à être ajoutés au plug-in. Si vous souhaitez remplacer la validation de certificat, décochez la case pour que toutes les matrices de stockage puissent être ajoutées au plug-in à l'aide de certificats auto-signés. Pour en savoir plus sur les certificats, reportez-vous à l'aide en ligne disponible à partir de l'interface du plug-in.

. Lorsque le message serveur Web démarré apparaît, cliquez sur *OK* pour terminer l'installation, puis cliquez sur *terminé*.
. Vérifiez que le serveur d'applications a bien été installé en exécutant la commande *services.msc*.
. Vérifiez que le service serveur d'applications (VCP) *le plug-in de stockage NetApp SANtricity pour vCenter* a été installé et que le service a démarré.
+

NOTE: Si nécessaire, vous pouvez modifier les paramètres validation de certificat et Port de service Web après l'installation. Dans le répertoire d'installation, ouvrez le fichier wsconfig.xml. Pour supprimer la validation de certificat sur les matrices de stockage, modifiez le `env` clé, `trust.all.arrays`, à `true`. Pour modifier le port Web Services, modifiez le `sslport` valeur de la valeur de port souhaitée comprise entre 0 et 65535. Assurez-vous que le numéro de port utilisé ne se lie pas à un autre processus. Lorsque vous avez terminé, enregistrez les modifications et redémarrez le serveur Web du plug-in. Si la valeur de port du serveur Web du plug-in est modifiée après l'enregistrement du plugin sur un vCSA, alors vous devez annuler l'enregistrement et réenregistrer le plugin pour que le vCSA communique sur le port modifié au serveur Web du plugin.





== Enregistrez le plug-in avec une appliance vCenter Server

Une fois le logiciel du plug-in installé, enregistrez le plugin avec un vCSA.


NOTE: Le plug-in ne peut être enregistré que sur un seul vCSA à la fois. Pour vous inscrire à une autre version de vCSA, vous devez annuler l'enregistrement du plug-in à partir de la version actuelle de vCSA et le désinstaller à partir de l'hôte de l'application. Vous pouvez ensuite réinstaller le plug-in et l'enregistrer dans l'autre vCSA.

. Ouvrez une invite via la ligne de commande et accédez au répertoire suivant :
+
`<install directory>\vcenter-register\bin`

. Exécutez le fichier *vcenter-register.bat* :
`vcenter-register.bat ^
    -action registerPlugin ^
    -vcenterHostname <vCenter FQDN> ^
    -username <Administrator username> ^`
. Vérifiez que le script a réussi.


Les journaux sont enregistrés dans `%install_dir%/working/logs/vc-registration.log`.



== Vérifiez l'enregistrement du plug-in

Une fois le plug-in installé et le script d'enregistrement exécuté, vérifiez que le plug-in a bien été enregistré avec vCenter Server Appliance.

. Ouvrez le client vSphere vers l'appliance vCenter Server.
. Dans la barre de menus, sélectionnez menu:Administrator[Plugins client].
. Assurez-vous que le plug-in de stockage pour vCenter est répertorié comme *activé*.
+
Si le plug-in est répertorié comme désactivé et qu'un message d'erreur indique qu'il ne peut pas communiquer avec le serveur d'applications, vérifiez que le numéro de port défini pour le serveur d'applications est activé pour passer par tous les pare-feu susceptibles d'être utilisés. Le numéro de port TCP (transmission Control Protocol) du serveur d'applications par défaut est 8445.


