---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-what-settings-are-imported.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 'La fonction Importer les paramètres est une opération par lots qui charge les configurations d"une matrice de stockage à plusieurs matrices de stockage. Les paramètres importés lors de cette opération dépendent de la configuration de la baie de stockage source dans System Manager.' 
---
= Quels paramètres sont importés ?
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La fonction Importer les paramètres est une opération par lots qui charge les configurations d'une matrice de stockage à plusieurs matrices de stockage.

Les paramètres importés lors de cette opération dépendent de la configuration de la baie de stockage source dans System Manager. Les paramètres suivants peuvent être importés dans plusieurs matrices de stockage :

* *Alertes par e-mail* -- les paramètres incluent une adresse de serveur de messagerie et les adresses e-mail des destinataires de l'alerte.
* *Syslog Alerts* -- les paramètres incluent une adresse de serveur syslog et un port UDP.
* *Alertes SNMP* -- les paramètres incluent un nom de communauté et une adresse IP pour le serveur SNMP.
* *AutoSupport* -- les paramètres incluent les fonctionnalités séparées (AutoSupport de base, AutoSupport OnDemand et diagnostic à distance), la fenêtre de maintenance, la méthode de livraison, et les plannings d'intervention.
* *Services d'annuaire* -- la configuration inclut le nom de domaine et l'URL d'un serveur LDAP (Lightweight Directory Access Protocol), ainsi que les mappages entre les groupes d'utilisateurs du serveur LDAP et les rôles prédéfinis de la baie de stockage.
* *Configuration du stockage* -- les configurations comprennent les volumes (uniquement les volumes non-référentiels et épais), les groupes de volumes, les pools et les affectations de disques de secours.
* *Paramètres système* -- les configurations incluent les paramètres de lecture des supports pour un volume, la mémoire cache SSD pour les contrôleurs et l'équilibrage automatique de la charge (n'inclut pas les rapports de connectivité hôte).

