---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-create-a-volume-group.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 'Vous pouvez créer un groupe de volumes pour un ou plusieurs volumes accessibles à l"hôte.' 
---
= Créer un groupe de volumes
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez créer un groupe de volumes pour un ou plusieurs volumes accessibles à l'hôte. Un groupe de volumes est un conteneur pour les volumes dont les caractéristiques sont partagées telles que le niveau RAID et la capacité.

.Avant de commencer
Consultez les directives suivantes :

* Vous avez besoin d'au moins un lecteur non affecté.
* Il existe des limites quant à la capacité de disque pouvant être utilisée dans un seul groupe de volumes. Ces limites varient en fonction de votre type d'hôte.
* Pour activer la protection contre la perte des tiroirs/tiroirs, vous devez créer un groupe de volumes qui utilise des disques situés dans au moins trois tiroirs ou tiroirs, sauf si vous utilisez RAID 1, où deux tiroirs sont le minimum.
* Lors de la configuration d'une baie de stockage EF600 ou EF300, assurez-vous que chaque contrôleur a accès à un nombre égal de disques dans les 12 premiers emplacements et à un nombre égal de disques dans les 12 derniers slots. Cette configuration permet aux contrôleurs d'utiliser plus efficacement les deux bus PCIe côté disque. Le système permet actuellement de sélectionner un lecteur sous la fonction Avancé lors de la création d'un groupe de volumes.


Vérifiez la façon dont votre choix du niveau RAID affecte la capacité résultante du groupe de volumes.

* Si vous sélectionnez RAID 1, vous devez ajouter deux lecteurs à la fois pour vous assurer qu'une paire en miroir est sélectionnée. La mise en miroir et la répartition (appelée RAID 10 ou RAID 1+0) sont réalisées lorsque quatre disques ou plus sont sélectionnés.
* Si vous sélectionnez RAID 5, vous devez ajouter au moins trois lecteurs pour créer le groupe de volumes.
* Si vous sélectionnez RAID 6, vous devez ajouter au moins cinq lecteurs pour créer le groupe de volumes.


.Description de la tâche
Lors de la création d'un groupe de volumes, vous déterminez les caractéristiques du groupe, telles que le nombre de disques, les fonctionnalités de sécurité, l'assurance des données, la protection contre les pertes de tiroirs et la protection contre les pertes de tiroirs.

Pour les baies de stockage EF600 et EF300, les paramètres comprennent également le provisionnement des ressources, la taille des blocs de disque et la taille des blocs de volume.


NOTE: De plus, des disques de capacité supérieure et la possibilité de répartir les volumes entre les contrôleurs permettent de créer plusieurs volumes par groupe de volumes et d'utiliser la capacité de stockage et de protéger vos données.

.Étapes
. Dans la page gérer, sélectionnez la matrice de stockage du groupe de volumes.
. Menu sélection:Provisioning [Configure pools and Volume Groups].
. Cliquez sur menu:Créer [Groupe de volumes].
+
La boîte de dialogue Créer un groupe de volumes s'affiche.

. Saisissez un nom pour le groupe de volumes.
. Sélectionnez le niveau RAID qui répond le mieux à vos besoins en termes de stockage et de protection des données. La table de sélection de groupes de volumes apparaît et affiche uniquement les candidats qui prennent en charge le niveau RAID sélectionné.
. (Facultatif) si vous disposez de plusieurs types de lecteur dans votre matrice de stockage, sélectionnez le type de lecteur que vous souhaitez utiliser.
+
Le tableau des candidats au groupe de volumes apparaît et affiche uniquement les candidats qui prennent en charge le type de disque sélectionné et le niveau RAID.

. (Facultatif) vous pouvez sélectionner la méthode automatique ou manuelle pour définir les lecteurs à utiliser dans le groupe de volumes. La méthode automatique est la sélection par défaut.
+

CAUTION: N'utilisez pas la méthode manuelle, sauf si vous êtes un expert qui comprend la redondance des lecteurs et des configurations de lecteurs optimales.

+
Pour sélectionner manuellement les lecteurs, cliquez sur le lien *sélection manuelle des lecteurs (avancé)*. Lorsque vous cliquez sur cette icône, la fonction devient *sélection automatique des lecteurs (Advanced)*.

+
La méthode manuelle vous permet de sélectionner les lecteurs spécifiques qui composent le groupe de volumes. Vous pouvez sélectionner des disques non assignés spécifiques pour obtenir la capacité dont vous avez besoin. Si la matrice de stockage contient des lecteurs de différents types de support ou de différents types d'interface, vous pouvez choisir uniquement la capacité non configurée pour un seul type de lecteur afin de créer le nouveau groupe de volumes.

. En fonction des caractéristiques de lecteur affichées, sélectionnez les lecteurs que vous souhaitez utiliser dans le groupe de volumes, puis cliquez sur *Créer*.


Les caractéristiques de conduite affichées dépendent de la méthode automatique ou manuelle sélectionnée. Pour plus d'informations, consultez la documentation relative à SANtricity System Manager, https://docs.netapp.com/us-en/e-series-santricity/sm-storage/create-volume-group.html["Créer un groupe de volumes"^].
