---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-import-storage-configuration-settings.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 'Importez la configuration de stockage d"une matrice de stockage vers d"autres matrices de stockage.' 
---
= Importer les paramètres de configuration du stockage
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez importer la configuration de stockage d'une matrice de stockage vers d'autres matrices de stockage. Cette opération de traitement par lot permet de gagner du temps lorsque vous devez configurer plusieurs baies sur le réseau.

.Avant de commencer
Assurez-vous que :

* Le stockage est configuré dans System Manager pour la baie de stockage que vous souhaitez utiliser comme source.
* La configuration existante des baies de stockage cibles est sauvegardée dans System Manager (menu:Paramètres[système > Enregistrer la configuration de la matrice de stockage]).
* Vous avez étudié les exigences en matière de réplication des configurations de stockage dans link:vc-olh-import-settings-overview.html["Vue d'ensemble des paramètres d'importation"].
* Les baies source et cible doivent répondre à ces exigences :
+
** Les tiroirs où les contrôleurs résident doivent être identiques.
** Les ID de tiroir doivent être identiques.
** Les tiroirs d'extension doivent être installés dans les mêmes emplacements avec les mêmes types de disques.
** Le type de boîtier RBOD doit être identique.
** Les HIC, y compris les fonctionnalités Data assurance de l'hôte, doivent être identiques.
** Les baies cibles doivent être en état optimal.
** La capacité de volume de la baie cible est supérieure à la capacité de la baie source.


* Vous comprenez les restrictions suivantes :
+
** L'importation d'une configuration recto-verso vers une configuration recto-verso n'est pas prise en charge. Cependant, l'importation d'une configuration recto-verso est autorisée.
** Les volumes de pool de disques de 64 To ou plus sur la baie source empêchent le processus d'importation sur les cibles.




.Description de la tâche
Les paramètres importés comprennent les volumes configurés (volumes épais et non référentiels uniquement), les groupes de volumes, les pools et les affectations de disques de secours.

.Étapes
. Dans la page gérer, cliquez sur menu:actions [Paramètres d'importation].
+
L'assistant Importer les paramètres s'ouvre.

. Dans la boîte de dialogue Sélectionner les paramètres, sélectionnez *Configuration de stockage*, puis cliquez sur *Suivant*.
+
Une boîte de dialogue s'ouvre pour sélectionner le tableau source.

. Dans la boîte de dialogue Sélectionner la source, sélectionnez la matrice avec les paramètres à importer, puis cliquez sur *Suivant*.
. Dans la boîte de dialogue Sélectionner des cibles, sélectionnez une ou plusieurs matrices pour recevoir les nouveaux paramètres.
+

NOTE: Les matrices de stockage avec un micrologiciel inférieur à 8.50 ne sont pas disponibles pour la sélection. En outre, une matrice n'apparaît pas dans cette boîte de dialogue si le plug-in ne peut pas communiquer avec cette matrice (par exemple, s'il est hors ligne ou s'il présente des problèmes de certificat, de mot de passe ou de mise en réseau).

. Cliquez sur *Terminer*.
+
La page opérations affiche les résultats de l'opération d'importation. Si l'opération échoue, vous pouvez cliquer sur sa ligne pour afficher plus d'informations.



.Résultat
Les baies de stockage cibles sont désormais configurées avec la même configuration de stockage que la baie source.
