---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-how-do-i-maintain-shelf-and-drawer-loss-protection.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Conservez la protection contre les pertes de tiroirs et de tiroirs pour un pool ou un groupe de volumes 
---
= Comment maintenir la protection contre les pertes des tablettes et des tiroirs ?
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Pour maintenir la protection contre les pertes de tiroirs et de tiroirs pour un pool ou un groupe de volumes, utilisez les critères spécifiés dans le tableau suivant.

|===
| Niveau | Critères pour la protection contre les pertes des étagères/tiroirs | Nombre minimum de tiroirs/étagères requis 


| Piscine | Pour les tiroirs, le pool ne doit pas contenir plus de deux disques dans un seul tiroir. Pour les tiroirs, le pool doit inclure un nombre égal de disques de chaque tiroir. | 6 pour les étagères 5 pour les tiroirs 


| RAID 6 | Le groupe de volumes ne contient pas plus de deux disques dans un tiroir ou un tiroir unique. | 3 


| RAID 3 ou RAID 5 | Chaque disque du groupe de volumes est situé dans un tiroir ou un tiroir séparé. | 3 


| RAID 1 | Chaque disque d'une paire en miroir doit être placé dans un tiroir ou un tiroir séparé. | 2 


| RAID 0 | Impossible d'obtenir une protection contre les pertes de tablette/tiroir. | Sans objet 
|===

NOTE: La protection contre les pertes de tiroirs/tiroirs n'est pas maintenue si un disque a déjà échoué dans le pool ou le groupe de volumes. Dans ce cas, si l'accès à un tiroir disque ou à un tiroir disque est perdu et par conséquent à un autre disque du pool ou du groupe de volumes, les données sont perdues.
