---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-redistribute-volumes.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Redistribuez les volumes pour déplacer de nouveau les volumes vers les propriétaires de contrôleur préférés 
---
= Redistribuez les volumes dans le plug-in de stockage SANtricity pour vCenter
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous redistribuez les volumes pour retransférer les volumes vers leurs propriétaires de contrôleur préférés. En général, les pilotes de chemins d'accès multiples déplacent les volumes depuis leur propriétaire privilégié de contrôleur en cas de problème lors du chemin d'accès aux données entre l'hôte et la baie de stockage.

.Avant de commencer
* Les volumes que vous souhaitez redistribuer ne sont pas en cours d'utilisation ou des erreurs d'E/S se produisent.
* Un pilote multivoie est installé sur tous les hôtes qui utilisent les volumes que vous souhaitez redistribuer, ou des erreurs d'E/S se produisent. Si vous souhaitez redistribuer les volumes sans pilote multivoie sur les hôtes, toutes les activités d'E/S des volumes pendant l'opération de redistribution doivent être arrêtées afin d'éviter les erreurs d'application.


.Description de la tâche
La plupart des pilotes de chemins d'accès multiples de l'hôte tentent d'accéder à chaque volume sur un chemin vers son propriétaire de contrôleur privilégié. Toutefois, si ce chemin préféré n'est plus disponible, le pilote multichemin de l'hôte bascule vers un autre chemin. Ce basculement peut entraîner le changement de propriété du volume vers le contrôleur secondaire. Une fois que vous avez résolu le problème à l'origine du basculement, certains hôtes peuvent retransférer automatiquement la propriété des volumes vers le propriétaire du contrôleur privilégié, mais dans certains cas, vous devrez peut-être redistribuer manuellement les volumes.

.Étapes
. Dans la page gérer, sélectionnez la matrice de stockage contenant les volumes que vous souhaitez redistribuer.
. Sélectionnez le menu:Provisioning [Manage volumes].
. Sélectionner menu:plus[rerépartir les volumes].
+
La boîte de dialogue redistribuer les volumes s'affiche. Tous les volumes de la matrice de stockage dont le propriétaire du contrôleur préféré ne correspond pas à son propriétaire actuel apparaissent dans cette boîte de dialogue.

. Sélectionnez un ou plusieurs volumes à redistribuer et confirmez que vous souhaitez effectuer l'opération.


.Résultat
Le système déplace les volumes sélectionnés vers les propriétaires de contrôleur préférés ou une boîte de dialogue de redistribution des volumes est peut-être inutile.
