---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-increase-capacity-of-a-volume.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Redimensionnez un volume pour augmenter sa capacité indiquée. 
---
= Augmentation de la capacité d'un volume
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous pouvez redimensionner un volume pour augmenter sa capacité indiquée.

.Avant de commencer
Assurez-vous que :

* Une capacité disponible suffisante est disponible dans le pool ou le groupe de volumes associé du volume.
* Le volume est optimal et ne présente aucun état de modification.
* Aucun disque de secours n'est utilisé dans le volume. (S'applique uniquement aux volumes de groupes de volumes.)


.Description de la tâche
Dans cette tâche, vous apprendrez à augmenter la capacité déclarée (la capacité signalée aux hôtes) d'un volume en utilisant la capacité disponible dans le pool ou le groupe de volumes. Veillez à prendre en compte vos besoins de capacité futurs pour d'autres volumes de ce pool ou de ce groupe de volumes.


NOTE: L'augmentation de la capacité d'un volume n'est prise en charge que sur certains systèmes d'exploitation. Si vous augmentez la capacité du volume sur un système d'exploitation hôte qui n'est pas pris en charge, la capacité étendue est inutilisable et vous ne pouvez pas restaurer la capacité du volume d'origine.

.Étapes
. Dans la page *Manage*, sélectionnez la matrice de stockage contenant les volumes à redimensionner.
. Sélectionnez le menu:Provisioning [Manage volumes].
. Sélectionnez le volume pour lequel vous souhaitez augmenter la capacité, puis sélectionnez *augmenter la capacité*.
+
La boîte de dialogue confirmer l'augmentation de la capacité s'affiche.

. Sélectionnez *Oui* pour continuer.
+
La boîte de dialogue augmenter la capacité déclarée s'affiche. Cette boîte de dialogue affiche la capacité actuelle signalée du volume et la capacité disponible dans le pool ou le groupe de volumes associé du volume.

. Utilisez la case *augmenter la capacité signalée en ajoutant...* pour ajouter de la capacité à la capacité actuellement disponible. Vous pouvez modifier la valeur de capacité pour l'afficher en mébioctets (Mio), gibioctets (Tio) ou tébioctets (Tio).
. Cliquez sur *augmenter*.
+
La capacité du volume est augmentée en fonction de votre sélection. Notez que cette opération peut être longue et peut affecter les performances du système.



.Une fois que vous avez terminé
Après avoir augmenté la capacité du volume, vous devez augmenter manuellement la taille du système de fichiers pour qu'elle corresponde. La façon dont vous faites cela dépend du système de fichiers que vous utilisez. Pour plus de détails, reportez-vous à la documentation du système d'exploitation hôte.
