---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-create-host-access.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Pour gérer le stockage avec le plug-in de stockage pour vCenter, vous devez découvrir ou définir chaque hôte du réseau. 
---
= Créez un accès hôte
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Pour gérer le stockage avec le plug-in de stockage pour vCenter, vous devez découvrir ou définir chaque hôte du réseau.

.Description de la tâche
En créant un hôte, vous définissez les paramètres de l'hôte pour fournir une connexion à la matrice de stockage et un accès E/S aux volumes.

Lorsque vous créez un hôte, gardez les consignes suivantes à l'esprit :

* Vous devez définir les ports d'identificateur d'hôte associés à l'hôte.
* Assurez-vous de fournir le même nom que le nom de système attribué à l'hôte.
* Cette opération n'a pas de succès si le nom que vous choisissez est déjà utilisé.
* La longueur du nom ne doit pas dépasser 30 caractères.


.Étapes
. Sur la page gérer, sélectionnez la matrice de stockage avec la connexion hôte.
. Sélectionnez menu:Provisioning [Configure Hosts].
+
La page configurer les hôtes s'ouvre.

. Cliquez sur menu:Créer [hôte].
+
La boîte de dialogue Créer un hôte s'affiche.

. Sélectionnez les paramètres de l'hôte, le cas échéant.
+
.Détails du champ
[%collapsible]
====
[cols="25h,~"]
|===
| Réglage | Description 


 a| 
Nom
 a| 
Saisissez un nom pour le nouvel hôte.



 a| 
Type de système d'exploitation hôte
 a| 
Sélectionnez le système d'exploitation en cours d'exécution sur le nouvel hôte dans la liste déroulante.



 a| 
Type d'interface hôte
 a| 
(Facultatif) si plusieurs types d'interface hôte sont pris en charge sur votre baie de stockage, sélectionnez le type d'interface hôte que vous souhaitez utiliser.



 a| 
Ports hôtes
 a| 
Effectuez l'une des opérations suivantes :

** *Sélectionner l'interface d'E/S* -- généralement, les ports d'hôte doivent avoir ouvert une session et être disponibles dans la liste déroulante. Vous pouvez sélectionner les identificateurs de port hôte dans la liste.
** *Ajout manuel* -- si un identificateur de port hôte n'est pas affiché dans la liste, cela signifie que le port hôte n'est pas connecté. Un utilitaire HBA ou l'utilitaire d'initiateur iSCSI peut être utilisé pour rechercher les identificateurs de port hôte et les associer à l'hôte. Vous pouvez saisir manuellement les identificateurs de port hôte ou les copier/coller à partir de l'utilitaire (un par un) dans le champ ports hôte. Vous devez sélectionner un identificateur de port hôte à la fois pour l'associer à l'hôte, mais vous pouvez continuer à sélectionner autant d'identificateurs qui sont associés à l'hôte. Chaque identifiant est affiché dans le champ ports hôte. Si nécessaire, vous pouvez également supprimer un identificateur en sélectionnant *X* en regard de celui-ci.




 a| 
Définissez le secret de l'initiateur CHAP
 a| 
(Facultatif) si vous avez sélectionné ou saisi manuellement un port hôte avec un IQN iSCSI, et si vous souhaitez avoir besoin d'un hôte qui tente d'accéder à la matrice de stockage pour s'authentifier à l'aide du protocole CHAP (Challenge Handshake Authentication Protocol), cochez la case « Set CHAP initiator secret » (définir le secret de l'initiateur CHAP). Pour chaque port hôte iSCSI que vous avez sélectionné ou saisi manuellement, procédez comme suit :

** Entrez le même code secret CHAP qui a été défini sur chaque initiateur hôte iSCSI pour l'authentification CHAP. Si vous utilisez l'authentification CHAP mutuelle (authentification bidirectionnelle permettant à un hôte de se valider sur la baie de stockage et pour qu'une baie de stockage se valide sur l'hôte), vous devez également définir le secret CHAP pour la baie de stockage lors de la configuration initiale ou en modifiant les paramètres.
** Laissez le champ vide si vous n'avez pas besoin d'une authentification de l'hôte. Actuellement, la seule méthode d'authentification iSCSI utilisée est CHAP.


|===
====
. Cliquez sur *Créer*.
. Si vous devez mettre à jour les informations sur l'hôte, sélectionnez-le dans le tableau et cliquez sur *Afficher/Modifier les paramètres*.


.Résultat
Une fois l'hôte créé, le système crée un nom par défaut pour chaque port hôte configuré pour l'hôte (libellé utilisateur). L'alias par défaut est `<Hostname_Port Number>`. Par exemple, l'alias par défaut du premier port créé pour l'IPT hôte est `IPT_1`.

.Une fois que vous avez terminé
Vous devez affecter un volume à un hôte afin qu'il puisse être utilisé pour les opérations d'E/S. Accédez à link:vc-olh-assign-volumes-to-hosts.html["Attribuez des volumes aux hôtes"].
