---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-why-can-i-not-increase-my-preservation-capacity.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Si vous avez créé des volumes sur toute la capacité utilisable disponible, il se peut que vous ne puissiez pas augmenter la capacité de préservation. 
---
= Pourquoi ne puis-je pas augmenter ma capacité de préservation ?
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Si vous avez créé des volumes sur toute la capacité utilisable disponible, il se peut que vous ne puissiez pas augmenter la capacité de préservation.

La capacité de conservation correspond à la capacité (nombre de disques) réservée dans un pool afin de prendre en charge les défaillances potentielles de disque. Lorsqu'un pool est créé, le système réserve automatiquement une quantité par défaut de capacité de conservation en fonction du nombre de disques du pool. Si vous avez créé des volumes sur toute la capacité utilisable disponible, vous ne pouvez pas augmenter la capacité de préservation sans ajouter de la capacité au pool en ajoutant des disques ou en supprimant des volumes.

Vous pouvez modifier la capacité de conservation des pools et des groupes de volumes. Sélectionnez le pool que vous souhaitez modifier. Cliquez sur *Afficher/Modifier les paramètres*, puis sélectionnez l'onglet *Paramètres*.


NOTE: La capacité de conservation est spécifiée comme un nombre de disques, même si la capacité de conservation réelle est répartie sur tous les disques du pool.
