---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-consolidate-free-capacity-for-a-volume-group.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 'Utilisez l"option consolider la capacité libre pour consolider les extensions libres existantes sur un groupe de volumes sélectionné. En exécutant cette action, vous pouvez créer des volumes supplémentaires à partir de la capacité maximale disponible dans un groupe de volumes.' 
---
= Consolidez la capacité disponible d'un groupe de volumes dans le plug-in de stockage SANtricity pour vCenter
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Utilisez l'option consolider la capacité libre pour consolider les extensions libres existantes sur un groupe de volumes sélectionné. En exécutant cette action, vous pouvez créer des volumes supplémentaires à partir de la capacité maximale disponible dans un groupe de volumes.

.Avant de commencer
* Le groupe de volumes doit contenir au moins une zone de capacité libre.
* Tous les volumes du groupe de volumes doivent être en ligne et à l'état optimal.
* Les opérations de modification de volume ne doivent pas être en cours, telles que la modification de la taille du segment d'un volume.


.Description de la tâche
Vous ne pouvez pas annuler l'opération après son démarrage. Vos données restent accessibles lors de l'opération de consolidation.

Vous pouvez lancer la boîte de dialogue consolider la capacité libre en utilisant l'une des méthodes suivantes :

* Lorsqu'au moins une zone de capacité libre est détectée pour un groupe de volumes, la recommandation consolider la capacité libre s'affiche sur la page d'accueil de la zone notification. Cliquez sur le lien *consolider la capacité libre* pour lancer la boîte de dialogue.
* Vous pouvez également lancer la boîte de dialogue consolider la capacité libre à partir de la page pools et groupes de volumes, comme décrit dans la tâche suivante.


.En savoir plus sur les zones de capacité disponibles
[%collapsible]
====
Une zone de capacité libre est la capacité disponible pouvant résulter de la suppression d'un volume ou de l'absence de toute capacité disponible lors de la création du volume. Lorsque vous créez un volume dans un groupe de volumes disposant d'une ou plusieurs zones de capacité libre, la capacité du volume est limitée à la plus grande zone de capacité libre de ce groupe de volumes. Par exemple, si un groupe de volumes dispose d'une capacité libre totale de 15 Gio et si la zone la plus large de capacité libre est de 10 Gio, le plus grand volume possible est de 10 Gio.

Vous consolidez la capacité disponible sur un groupe de volumes afin d'améliorer les performances d'écriture. La capacité libre de votre groupe de volumes se fragmentera au fil du temps au fur et à mesure que l'hôte écrit, modifie et supprime des fichiers. Finalement, la capacité disponible ne sera pas située dans un seul bloc contigu, mais sera dispersée en petits fragments dans le groupe de volumes. Cela entraîne une fragmentation supplémentaire des fichiers, car l'hôte doit écrire de nouveaux fichiers sous forme de fragments pour les insérer dans les plages disponibles des clusters libres.

En consolidant la capacité disponible sur un groupe de volumes sélectionné, vous remarquerez une amélioration des performances du système de fichiers chaque fois que l'hôte écrit de nouveaux fichiers. Le processus de consolidation permettra également d'éviter que de nouveaux fichiers ne soient fragmentés à l'avenir.

====
.Étapes
. Sur la page gérer, sélectionnez la matrice de stockage contenant le groupe de volumes.
. Menu sélection:Provisioning [Configure pools and Volume Groups].
. Sélectionnez le groupe de volumes disposant de la capacité libre que vous souhaitez consolider, puis sélectionnez menu:tâches rares[consolider la capacité libre du groupe de volumes].
+
La boîte de dialogue consolider la capacité libre s'affiche.

. Type `consolidate` pour confirmer que vous souhaitez effectuer cette opération.
. Cliquez sur *consolider*.


.Résultat
Le système commence à consolider (défragmenter) les zones de capacité libre du groupe de volumes en une quantité contiguë pour les tâches de configuration du stockage ultérieures.

.Une fois que vous avez terminé
Dans la barre latérale de navigation, sélectionnez *opérations* pour afficher la progression de l'opération consolider la capacité libre. Cette opération peut être longue et peut affecter les performances du système.
