---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-change-storage-array-passwords.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Mettez à jour les mots de passe utilisés pour afficher et accéder aux matrices de stockage dans le plug-in de stockage pour vCenter. 
---
= Changer les mots de passe des matrices de stockage
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous pouvez mettre à jour les mots de passe utilisés pour afficher et accéder aux baies de stockage dans le plug-in de stockage pour vCenter.

.Avant de commencer
Vous devez connaître le mot de passe actuel de la baie de stockage, qui est défini dans System Manager.

.Description de la tâche
Dans cette tâche, vous entrez le mot de passe actuel d'une matrice de stockage afin que vous puissiez y accéder dans le plug-in. Cela peut être nécessaire si le mot de passe de la matrice a été modifié dans System Manager.

.Étapes
. Dans la page *gérer*, sélectionnez une ou plusieurs matrices de stockage.
. Menu sélection:tâches rares[fournir des mots de passe de matrice de stockage].
. Entrez le mot de passe ou les mots de passe pour chaque matrice de stockage, puis cliquez sur *Enregistrer*.

