---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-how-do-i-view-and-interpret-all-ssd-cache-statistics.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Vous pouvez afficher les statistiques nominales et les statistiques détaillées de SSD cache. 
---
= Comment afficher et interpréter toutes les statistiques SSD cache ?
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous pouvez afficher les statistiques nominales et les statistiques détaillées de SSD cache.

Les statistiques nominales sont un sous-ensemble des statistiques détaillées. Les statistiques détaillées ne peuvent être affichées que lorsque vous exportez toutes les statistiques SSD dans un fichier .csv. Pendant que vous examinez et interprétez les statistiques, gardez à l'esprit que certaines interprétations sont dérivées en examinant une combinaison de statistiques.



=== Statistiques nominales

Pour afficher les statistiques de cache SSD, accédez à la page *gérer*. Menu sélection:Provisioning [Configure pools & Volume Groups]. Sélectionnez le cache SSD pour lequel vous souhaitez afficher les statistiques, puis sélectionnez menu:More[Afficher les statistiques]. Les statistiques nominales sont affichées dans la boîte de dialogue Afficher les statistiques du cache SSD.


NOTE: Cette fonctionnalité n'est pas disponible sur les systèmes de stockage EF600 ou EF300.

La liste inclut des statistiques nominales, qui sont un sous-ensemble des statistiques détaillées.



=== Statistiques détaillées

Les statistiques détaillées comprennent les statistiques nominales, ainsi que des statistiques supplémentaires. Ces statistiques supplémentaires sont enregistrées avec les statistiques nominales, mais, contrairement aux statistiques nominales, elles ne s'affichent pas dans la boîte de dialogue Afficher les statistiques de cache des disques SSD. Vous ne pouvez consulter les statistiques détaillées qu'après avoir exporté les statistiques vers un fichier .csv.

Les statistiques détaillées sont répertoriées après les statistiques nominales.
