---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-view-certificates.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 'Afficher les informations récapitulatives d"un certificat, y compris l"organisation utilisant le certificat, l"autorité qui a émis le certificat, la période de validité et les empreintes digitales (identifiants uniques)' 
---
= Afficher les certificats
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez afficher les informations récapitulatives d'un certificat, y compris l'organisation utilisant le certificat, l'autorité qui a émis le certificat, la période de validité et les empreintes digitales (identifiants uniques).

.Étapes
. Sélectionnez *gestion des certificats*.
. Sélectionnez l'un des onglets suivants :
+
** *Management* -- affiche le certificat pour le système hébergeant le plugin. Un certificat de gestion peut être auto-signé ou approuvé par une autorité de certification (AC). Il permet un accès sécurisé au plug-in.
** *Trusted* -- affiche les certificats que le plug-in peut accéder aux matrices de stockage et aux autres serveurs distants, tels qu'un serveur LDAP. Les certificats peuvent être émis par une autorité de certification (CA) ou être auto-signés.


. Pour plus d'informations sur un certificat, sélectionnez sa ligne, les points de suspension à la fin de la ligne, puis cliquez sur *View* ou *Export*.

