---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-why-do-i-not-see-all-my-volumes,-hosts,-or-host-clusters.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 'Les volumes snapshot avec un volume de base DA ne peuvent pas être affectés à un hôte qui ne prend pas en charge Data assurance (DA).' 
---
= Pourquoi ne pas voir tous mes volumes, hôtes ou clusters hôtes ?
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Les volumes snapshot avec un volume de base DA ne peuvent pas être affectés à un hôte qui ne prend pas en charge Data assurance (DA). Vous devez désactiver DA sur le volume de base avant qu'un volume d'instantané ne puisse être affecté à un hôte qui n'est pas compatible DA.

Prenez en compte les consignes suivantes concernant l'hôte auquel vous attribuez le volume de snapshot :

* Un hôte n'est pas compatible DA s'il est connecté à la matrice de stockage via une interface d'E/S qui n'est pas compatible DA.
* Un cluster hôte n'est pas compatible DA s'il possède au moins un membre hôte qui n'est pas compatible DA.



NOTE: Vous ne pouvez pas désactiver DA sur un volume associé aux snapshots (groupes de cohérence, groupes Snapshot, images Snapshot et volumes Snapshot), copies de volume, et miroirs. Tous les objets de snapshot et de capacité réservés associés doivent être supprimés pour que l'agent de DA puisse être désactivé sur le volume de base.
