---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-what-is-the-default-cluster.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 'Le cluster par défaut est une entité définie par le système qui permet à tout identificateur de port hôte non associé connecté à la matrice de stockage d"accéder aux volumes affectés au cluster par défaut.' 
---
= À quoi correspond le cluster par défaut ?
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le cluster par défaut est une entité définie par le système qui permet à tout identificateur de port hôte non associé connecté à la matrice de stockage d'accéder aux volumes affectés au cluster par défaut.

Un identificateur de port hôte non associé est un port hôte qui n'est pas logiquement associé à un hôte donné mais qui est physiquement installé dans un hôte et connecté à la matrice de stockage.


NOTE: Si vous souhaitez que les hôtes disposent d'un accès spécifique à certains volumes de la matrice de stockage, vous ne devez pas utiliser le cluster par défaut. À la place, vous devez associer les identificateurs de port hôte à leurs hôtes correspondants. Cette tâche peut être effectuée manuellement pendant l'opération Créer un hôte. Ensuite, vous affectez des volumes à un hôte individuel ou à un cluster hôte.

Vous ne devez utiliser le cluster par défaut que dans des situations spéciales où votre environnement de stockage externe est recommandé pour permettre à tous les hôtes et tous les identifiants de port hôte connectés à la baie de stockage ont accès à tous les volumes (mode tout accès). sans spécifiquement faire connaître les hôtes à la matrice de stockage ou à l'interface utilisateur.

Initialement, vous pouvez affecter des volumes uniquement au cluster par défaut via l'interface de ligne de commande. Cependant, après avoir affecté au moins un volume au cluster par défaut, cette entité (appelée cluster par défaut) s'affiche dans l'interface utilisateur dans laquelle vous pouvez alors gérer cette entité.
