---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-array-groups-overview.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Gérez votre infrastructure physique et virtualisée en regroupant un ensemble de baies de stockage. 
---
= Vue d'ensemble des groupes de matrices
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez gérer votre infrastructure physique et virtualisée dans le plug-in de stockage pour vCenter en regroupant un ensemble de baies de stockage. Vous pouvez regrouper les baies de stockage par groupe pour faciliter l'exécution des tâches de surveillance ou de reporting.

Types de matrices de stockage :

* *All Group* -- le groupe All est le groupe par défaut et inclut toutes les matrices de stockage découvertes dans votre organisation. Le groupe tous est accessible depuis la vue principale.
* *Groupe créé par l'utilisateur* -- Un groupe créé par l'utilisateur comprend les matrices de stockage que vous sélectionnez manuellement pour ajouter à ce groupe. Les groupes créés par l'utilisateur sont accessibles depuis la vue principale.

