---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-delete-volume.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 'Supprimez un ou plusieurs volumes pour augmenter la capacité disponible d"un pool ou d"un groupe de volumes.' 
---
= Supprimez le volume dans le plug-in de stockage SANtricity pour vCenter
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous pouvez supprimer un ou plusieurs volumes pour augmenter la capacité disponible d'un pool ou d'un groupe de volumes.

.Avant de commencer
Sur les volumes que vous prévoyez de supprimer, vérifiez que :

* Toutes les données sont sauvegardées.
* Toutes les entrées/sorties (E/S) sont arrêtées.
* Tous les périphériques et systèmes de fichiers sont démontés.


.Description de la tâche
Généralement, vous supprimez des volumes si ceux-ci ont été créés avec des paramètres ou une capacité incorrects, ou si la configuration du stockage n'est plus adaptée. La suppression d'un volume augmente la capacité disponible dans le pool ou le groupe de volumes.


CAUTION: La suppression d'un volume entraîne la perte de toutes les données présentes sur ces volumes.

N'oubliez pas que vous ne pouvez pas supprimer un volume qui a l'une des conditions suivantes :

* Le volume est en cours d'initialisation.
* Le volume est en cours de reconstruction.
* Le volume fait partie d'un groupe de volumes qui contient un lecteur en cours d'opération de copie.
* Le volume est en cours d'opération de modification, par exemple un changement de taille de segment, à moins que le volume ne soit à présent en état d'échec.
* Le volume contient n'importe quel type de réservation persistante.
* Le volume est un volume source ou cible d'un volume de copie dont l'état est en attente, en cours ou en échec.



NOTE: Lorsqu'un volume dépasse une taille donnée (actuellement 128 To), l'opération de suppression est effectuée en arrière-plan et l'espace libéré risque de ne pas être immédiatement disponible.

.Étapes
. Dans la page *Manage*, sélectionnez la matrice de stockage contenant les volumes à supprimer.
. Sélectionnez le menu:Provisioning [Manage volumes].
. Cliquez sur *Supprimer*.
+
La boîte de dialogue Supprimer les volumes s'affiche.

. Sélectionnez un ou plusieurs volumes à supprimer, puis confirmez que vous souhaitez effectuer l'opération.
. Cliquez sur *Supprimer*.

