---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-what-raid-level-is-best-for-my-application.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 'Pour optimiser les performances d"un groupe de volumes, vous devez sélectionner le niveau RAID approprié.' 
---
= Quel est le niveau RAID le mieux adapté à mon application ?
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Pour optimiser les performances d'un groupe de volumes, vous devez sélectionner le niveau RAID approprié.

Vous pouvez déterminer le niveau RAID approprié en connaissant les pourcentages de lecture et d'écriture des applications qui accèdent au groupe de volumes. Utilisez la page performances pour obtenir ces pourcentages.



== Niveaux RAID et performances applicatives

Le RAID repose sur une série de configurations appelées niveaux pour déterminer comment les données utilisateur et de redondance sont écrites et extraites des lecteurs. Chaque niveau RAID offre des fonctions de performance différentes. Les applications présentant un pourcentage de lecture élevé peuvent être utilisées avec des volumes RAID 5 ou RAID 6 en raison des performances de lecture exceptionnelles des configurations RAID 5 et RAID 6.

Les applications dont le pourcentage de lecture est faible (intensives en écriture) ne fonctionnent pas aussi bien sur les volumes RAID 5 ou RAID 6. La dégradation des performances résulte de la façon dont un contrôleur écrit les données et les données de redondance sur les disques d'un groupe de volumes RAID 5 ou RAID 6.

Sélectionnez un niveau RAID en fonction des informations suivantes.



=== RAID 0

*Description:*

* Mode de répartition non redondant.
* RAID 0 répartit les données dans tous les disques du groupe de volumes.


*Fonctionnalités de protection des données:*

* RAID 0 n'est pas recommandé pour les besoins en haute disponibilité. Le RAID 0 est meilleur pour les données non stratégiques.
* Si un seul disque tombe en panne dans le groupe de volumes, tous les volumes associés sont défaillants et toutes les données sont perdues.


*Nombre de disques requis :*

* Un minimum d'un lecteur est requis pour le niveau RAID 0.
* Les groupes de volumes RAID 0 peuvent avoir plus de 30 disques.
* Vous pouvez créer un groupe de volumes qui inclut tous les disques de la matrice de stockage.




=== RAID 1 ou RAID 10

*Description:*

* Mode répartition/miroir.


*Fonctionnement:*

* RAID 1 utilise la mise en miroir des disques pour écrire des données sur deux disques dupliqués simultanément.
* RAID 10 répartit les données sur un ensemble de paires de disques en miroir à l'aide de bandes de disques.


*Fonctionnalités de protection des données:*

* RAID 1 et RAID 10 offrent des performances élevées et une disponibilité des données optimale.
* RAID 1 et RAID 10 utilisent la mise en miroir des lecteurs pour effectuer une copie exacte d'un lecteur vers un autre.
* Si l'un des lecteurs d'une paire de disques tombe en panne, la matrice de stockage peut basculer instantanément vers l'autre disque sans perte de données ni de service.
* Une seule panne de disque entraîne l'dégradation des volumes associés. Le lecteur miroir permet d'accéder aux données.
* Une défaillance de paire de disques dans un groupe de volumes entraîne la défaillance de tous les volumes associés, ce qui risque d'entraîner la perte de données.


*Nombre de disques requis :*

* Un minimum de deux lecteurs est requis pour RAID 1 : un lecteur pour les données utilisateur et un lecteur pour les données en miroir.
* Si vous sélectionnez quatre lecteurs ou plus, RAID 10 est automatiquement configuré sur le groupe de volumes : deux lecteurs pour les données utilisateur et deux lecteurs pour les données en miroir.
* Vous devez avoir un nombre pair de lecteurs dans le groupe de volumes. Si vous ne disposez pas d'un nombre pair de disques et que vous disposez de disques non affectés restants, accédez à *pools et groupes de volumes* pour ajouter des disques supplémentaires au groupe de volumes, puis réessayez l'opération.
* Les groupes de volumes RAID 1 et RAID 10 peuvent avoir plus de 30 disques. Il est possible de créer un groupe de volumes qui inclut tous les disques de la matrice de stockage.




=== RAID 5

*Description:*

* Mode d'E/S élevé.


*Fonctionnement:*

* Les données utilisateur et les informations redondantes (parité) sont réparties entre les disques.
* La capacité équivalente d'un lecteur est utilisée pour des informations redondantes.


*Fonctionnalités de protection des données*

* Si un seul disque tombe en panne au sein d'un groupe de volumes RAID 5, tous les volumes associés sont dégradés. Les informations redondantes permettent de toujours accéder aux données.
* Si deux disques ou plus tombent en panne dans un groupe de volumes RAID 5, tous les volumes associés sont défaillants et toutes les données sont perdues.


*Nombre de disques requis :*

* Vous devez avoir au moins trois lecteurs dans le groupe de volumes.
* En règle générale, vous êtes limité à 30 disques au maximum dans le groupe de volumes.




=== RAID 6

*Description:*

* Mode d'E/S élevé.


*Fonctionnement:*

* Les données utilisateur et les informations redondantes (double parité) sont réparties sur les lecteurs.
* La capacité équivalente de deux disques est utilisée pour des informations redondantes.


*Fonctionnalités de protection des données:*

* Si un ou deux disques tombent en panne dans un groupe de volumes RAID 6, tous les volumes associés sont dégradés, mais les informations redondantes permettent de toujours accéder aux données.
* Si un groupe de volumes RAID 6 contient trois disques ou plus, tous les volumes associés sont défaillants et toutes les données sont perdues.


*Nombre de disques requis :*

* Vous devez avoir au moins cinq disques dans le groupe de volumes.
* En règle générale, vous êtes limité à 30 disques au maximum dans le groupe de volumes.



NOTE: Vous ne pouvez pas modifier le niveau RAID d'un pool. L'interface utilisateur configure automatiquement les pools en tant que RAID 6.



== Niveaux RAID et protection des données

RAID 1, RAID 5 et RAID 6 écrivent les données de redondance sur le support du lecteur pour la tolérance aux pannes. Les données de redondance peuvent être une copie des données (mises en miroir) ou un code de correction d'erreur dérivé des données. En cas de panne d'un disque, vous pouvez utiliser les données redondantes pour reconstruire rapidement les informations sur un disque de remplacement.

Vous configurez un seul niveau RAID sur un seul groupe de volumes. Toutes les données de redondance de ce groupe de volumes sont stockées dans le groupe de volumes. La capacité du groupe de volumes est la capacité d'agrégat des disques membres moins la capacité réservée aux données de redondance. La capacité nécessaire à la redondance dépend du niveau RAID utilisé.
