---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-when-would-i-want-to-use-the-assign-host-later-selection.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 'Pour accélérer le processus de création de volumes, vous pouvez ignorer l"étape d"affectation des hôtes afin que les nouveaux volumes soient initialisés hors ligne.' 
---
= Quand dois-je utiliser la sélection attribuer l'hôte ultérieurement ?
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Pour accélérer le processus de création de volumes, vous pouvez ignorer l'étape d'affectation des hôtes afin que les nouveaux volumes soient initialisés hors ligne.

Les volumes qui viennent d'être créés doivent être initialisés. Le système peut les initialiser à l'aide de l'un des deux modes suivants : un processus d'initialisation en arrière-plan IAF (format disponible immédiat) ou un processus hors ligne.

Lorsque vous mappez un volume à un hôte, tous les volumes en cours d'initialisation de ce groupe passent à l'initialisation en arrière-plan. Ce processus d'initialisation en arrière-plan permet d'effectuer des E/S simultanées des hôtes, ce qui peut parfois prendre du temps.

Lorsqu'aucun volume d'un groupe de volumes n'est mappé, l'initialisation hors ligne est effectuée. Le processus hors ligne est bien plus rapide qu'en arrière-plan.
