---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-clear-staged-os-software.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 'Vous pouvez supprimer le logiciel OS préparé pour vous assurer qu"une version en attente n"est pas activée par inadvertance ultérieurement.' 
---
= Effacez le logiciel du système d'exploitation par étape
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez supprimer le logiciel OS préparé pour vous assurer qu'une version en attente n'est pas activée par inadvertance ultérieurement. La suppression du logiciel du système d'exploitation intermédiaire n'affecte pas la version actuelle exécutée sur les matrices de stockage.

.Étapes
. Dans la vue principale, sélectionnez *gérer*, puis menu:Centre de mise à niveau[Effacer le logiciel SANtricity par étapes].
+
La boîte de dialogue Effacer le logiciel SANtricity par étapes s'ouvre et répertorie tous les systèmes de stockage détectés avec le logiciel en attente ou la NVSRAM.

. Si nécessaire, filtrez ou triez les systèmes de stockage dans la liste pour afficher tous les systèmes équipés de logiciels par étapes.
. Cochez les cases des systèmes de stockage avec le logiciel en attente que vous souhaitez supprimer.
. Cliquez sur *Effacer*.
+
L'état de l'opération est indiqué dans la boîte de dialogue.


