---
permalink: install-hw-cabling/index.html 
sidebar: sidebar 
keywords: cabling, cables, E-Series, eseries, E2800, E5700, EF300, EF600, DE212C, DE224C, DE460C 
summary: Connectez un hôte directement à un contrôleur ou utilisez des commutateurs. 
---
= Câblage de votre système de stockage - E-Series
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez connecter un hôte directement à un contrôleur ou utiliser des commutateurs pour connecter un hôte à un contrôleur.

Si votre système de stockage inclut un ou plusieurs tiroirs disques, vous devez les connecter à votre tiroir contrôleur. Vous pouvez ajouter un nouveau tiroir disque alors que l'alimentation est toujours appliquée à d'autres composants du système de stockage. En outre, vous pouvez connecter votre système de stockage à un réseau pour une gestion hors bande.

Les informations de câblage sont destinées à un installateur de matériel ou à un administrateur système qui installe ou développe un système de stockage. Il est supposé que vous avez installé le système de stockage comme décrit dans les _instructions d'installation et de configuration_ pour votre matériel.



[[applicable-hardware-model]]
== Modèle matériel applicable

Les informations de câblage s'appliquent aux modèles matériels suivants.


NOTE: Si votre baie de contrôleurs (système de stockage) n'est pas listée ci-dessous, consultez link:../getting-started/getup-run-concept.html["Démarrage rapide de la gamme E-Series"^] et cliquez sur le lien correspondant à votre système de stockage spécifique pour accéder aux informations de câblage.

|===
| * Étagère contrôleur* | *Étagère de disques* 


 a| 
EF300, EF600, EF300C, EF600C
 a| 
DE212C, DE224C, DE460



 a| 
E5724, EF570, E4012, E2812, E2824 ET EF280
 a| 
DE212C ET DE224C



 a| 
E4060, E2860, E5760
 a| 
DE460C

|===


[[additional-cabling-information]]
== Informations supplémentaires sur le câblage

Si vous effectuez un câblage pour l'une des configurations suivantes, consultez https://mysupport.netapp.com/ecm/ecm_download_file/ECMLP2859057["Ajout de tiroirs disques IOM à un tiroir contrôleur E27XX, E56XX ou EF560 existant."^]

|===
| * Étagère contrôleur* | *Étagère de disques* 


 a| 
E2712, E2724, E5612, E5624, EF560
 a| 
DE212C ET DE224C



 a| 
E2760, E5660
 a| 
DE460C

|===
Pour plus d'informations sur le câblage permettant de prendre en charge les fonctions de mise en miroir, consultez le https://www.netapp.com/pdf.html?item=/media/17133-tr4656.pdf["Guide de déploiement et description des fonctionnalités de mise en miroir synchrone et asynchrone"^].
