---
permalink: maintenance-e5700/hics-overview-supertask-concept.html 
sidebar: sidebar 
keywords: E5700 host interface card, E5700 HIC, replace E5700 HIC, failed E5700 HIC 
summary: Consultez les conditions relatives au remplacement de la carte E5700 HIC. 
---
= Conditions requises pour le remplacement de la carte E5700 HIC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'ajouter, de mettre à niveau ou de remplacer une carte d'interface hôte (HIC) dans un système E5700, vérifiez les conditions et les points à prendre en compte.



== Présentation de la procédure

Vous pouvez ajouter, mettre à niveau ou remplacer une HIC dans le tiroir contrôleur E5724 et le tiroir contrôleur E5760.

Voici une présentation des étapes à suivre pour remplacer une HIC dans des contrôleurs E5700 (E5760 ou E5724) :

. Mettre le contrôleur hors ligne
. Déposer le boîtier du contrôleur
. Remplacer la batterie
. Remplacez le boîtier du contrôleur
. Mettre le contrôleur en ligne




== Conditions requises pour l'ajout, la mise à niveau ou le remplacement d'une HIC

Si vous prévoyez d'ajouter, de mettre à niveau ou de remplacer une carte d'interface hôte (HIC), gardez les conditions suivantes à l'esprit.

* Vous devez planifier une fenêtre de maintenance des temps d'arrêt pour cette procédure. L'alimentation doit être éteinte lorsque vous installez des HIC. Vous ne pouvez donc pas accéder aux données sur la baie de stockage tant que cette procédure n'est pas terminée. (Dans une configuration duplex, cela est dû au fait que les deux contrôleurs doivent avoir la même configuration HIC lorsqu'ils sont sous tension.)
* Vous devez disposer de deux circuits intégrés compatibles avec vos contrôleurs.
+
Pour les configurations duplex (deux contrôleurs), les circuits intégrés installés dans les deux boîtiers de contrôleur doivent être identiques. La présence de circuits intégrés non concordants provoque le verrouillage du contrôleur avec la HIC de remplacement lorsque vous le met en ligne.

* Tous les câbles, émetteurs-récepteurs, commutateurs et adaptateurs de bus hôte (HBA) sont nécessaires pour connecter les nouveaux ports hôte.
+
Pour plus d'informations sur le matériel compatible, reportez-vous au https://mysupport.netapp.com/NOW/products/interoperability["Matrice d'interopérabilité NetApp"^] ou le http://hwu.netapp.com/home.aspx["NetApp Hardware Universe"^].

* Vous avez un bracelet ESD, ou vous avez pris d'autres précautions antistatiques.
* Vous avez un tournevis cruciforme n° 1.
* Vous disposez d'étiquettes pour identifier chaque câble connecté au boîtier du contrôleur.
* Vous disposez d'une station de gestion avec un navigateur qui peut accéder au gestionnaire système SANtricity du contrôleur. (Pour ouvrir l'interface System Manager, pointez le navigateur vers le nom de domaine ou l'adresse IP du contrôleur.)

