---
permalink: install-hw-e2800-e5700/e2824-e5724-install-setup-task.html 
sidebar: sidebar 
keywords: instruction, describe, install, storage, system, provide, link, additional, content, installation, setup, e5724, ef570, ef280, e2812, e2824, de212c, de224c 
summary: Ces instructions expliquent comment installer et configurer votre nouveau système de stockage et fournissent des liens vers des contenus supplémentaires. 
---
= Instructions d'installation et de configuration pour les systèmes E5724, EF570, EF280, E2812, E2824, DE212C et DE224C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ces instructions expliquent comment installer et configurer votre nouveau système de stockage et fournissent des liens vers des contenus supplémentaires.

Vous pouvez choisir l'un des formats suivants pour vous guider lors de l'installation et de la configuration de votre nouveau système de stockage.

* *PDF*
+
Il s'agit d'un PDF imprimable contenant des instructions étape par étape et des liens en direct vers du contenu supplémentaire.

+
** https://library.netapp.com/ecm/ecm_download_file/ECMLP2842063["E5724, EF570, EF280, E2812, E2824, Poster PDF DE212C et DE224C"^]


* *Instructions en ligne*
+
Voici les instructions de configuration décrites sur ce site. Commencez par un des sujets suivants.

+
** xref:e2824-e5724-prepare-task.adoc[Préparation à l'installation des systèmes E5724, EF570, EF280, E2812, E2824, DE212C et DE224C]



