---
permalink: config-windows/install-configure-host-utilities-task.html 
sidebar: sidebar 
keywords: Windows Unified Host Utilities, express Windows configuration, software configuration, Windows host, E2800, E5700, EF300, EF600, E-Series, eseries, SMcli, SMdevices 
summary: Installez la méthode Windows Unified Host Utilities pour Windows Express. 
---
= Installez et configurez les utilitaires d'hôtes unifiés Linux dans E-Series - Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les outils Windows Unified Host Utilities vous aident à connecter les ordinateurs hôtes aux systèmes de stockage NetApp et à définir les paramètres requis sur les ordinateurs hôtes. Vous pouvez également définir les délais de lecture et d'écriture appropriés pour les systèmes de stockage NetApp.


NOTE: Pour plus d'informations, reportez-vous au _Windows Host Utilities installation Guide (Guide d'installation des utilitaires d'hôtes Windows), disponible sous http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61343["Documentation NetApp : utilitaires hôtes"^].

.Étapes
. Utilisez le http://mysupport.netapp.com/matrix["Matrice d'interopérabilité NetApp"^] Pour déterminer la version appropriée d'Unified Host Utilities à installer.
+
Les versions sont répertoriées dans une colonne de chaque configuration prise en charge.

. Téléchargez les utilitaires d'hôtes unifiés à partir de http://mysupport.netapp.com["Support NetApp"^].
+

NOTE: Ce package d'utilitaires ne peut pas être installé à l'aide du programme d'installation de SANtricity Storage Manager.

+

NOTE: Vous pouvez également utiliser la commande SMcli `-identifyDevices` Pour exécuter les mêmes fonctions que l'outil Unified Host Utility. Le logiciel SMcli est inclus dans le système d'exploitation SANtricity et téléchargeable via SANtricity System Manager. Pour plus d'informations sur le téléchargement de SMcli via le Gestionnaire système SANtricity, reportez-vous au https://docs.netapp.com/us-en/e-series-santricity/sm-settings/download-cli.html["Téléchargez la rubrique de l'interface de ligne de commande dans l'aide en ligne de SANtricity System Manager"^].


