---
permalink: config-windows/install-storage-manager-for-smcli-task.html 
sidebar: sidebar 
keywords: install Storage Manager Windows, install CLI Windows, install command line interface, install Host Context Agent, install HCA, express Windows configuration, software configuration, Windows host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Installez Storage Manager pour CLI et HCA dans la méthode Windows Express. 
---
= Installation de SANtricity Storage Manager pour SMcli et de l'agent HCA (Host Context Agent)
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous utilisez le logiciel SANtricity 11.53 ou une version antérieure, vous pouvez installer le logiciel SANtricity Storage Manager sur votre station de gestion pour vous aider à gérer la baie.

SANtricity Storage Manager inclut l'interface de ligne de commande (CLI) pour des tâches de gestion supplémentaires, ainsi que l'agent de contexte hôte pour la communication des informations de configuration de l'hôte aux contrôleurs de la baie de stockage via le chemin d'E/S.


NOTE: Si vous utilisez le logiciel SANtricity 11.60 ou une version ultérieure, vous n'avez pas besoin de suivre ces étapes. L'interface de ligne de commande sécurisée SANtricity (SMcli) est inclus dans le système d'exploitation SANtricity et téléchargeable via SANtricity System Manager. Pour plus d'informations sur le téléchargement du SMcli via le Gestionnaire système SANtricity, reportez-vous à la rubrique _Télécharger l'interface de ligne de commande (CLI)_ de l'aide en ligne de SANtricity System Manager.

.Avant de commencer
Assurez-vous de disposer des éléments suivants :

* SANtricity 11.53 ou version antérieure.
* Les privilèges administrateur ou superutilisateur appropriés.
* Système pour le client SANtricity Storage Manager dont la configuration minimale requise est la suivante :
+
** *RAM* : 2 Go pour Java Runtime Engine
** *Espace disque* : 5 Go
** *OS/Architecture* : pour obtenir des conseils sur la détermination des versions et architectures de systèmes d'exploitation pris en charge, allez à http://mysupport.netapp.com["Support NetApp"^]. Dans l'onglet *Downloads*, accédez au menu :Downloads[E-Series SANtricity Storage Manager].




.Étapes
. Téléchargez la version du logiciel SANtricity sur http://mysupport.netapp.com["Support NetApp"^]. Dans l'onglet *Downloads*, menu :Downloads[E-Series SANtricity Storage Manager].
. Exécutez le programme d'installation de SANtricity. Double-cliquez sur le paquet d'installation SMIA*.exe à exécuter.
. Utilisez l'assistant d'installation pour installer le logiciel sur la station de gestion.

