---
permalink: config-windows/verify-windows-config-support-task.html 
sidebar: sidebar 
keywords: express Windows configuration, software configuration, Windows host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Vérifiez que la configuration Windows est prise en charge. 
---
= Vérifiez la prise en charge de la configuration Windows dans E-Series
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour assurer un fonctionnement fiable, créez un plan d'implémentation, puis vérifiez que l'ensemble de la configuration est pris en charge à l'aide de la matrice d'interopérabilité (IMT).

.Étapes
. Accédez au http://mysupport.netapp.com/matrix["Matrice d'interopérabilité NetApp"^].
. Cliquez sur la vignette *Storage solution Search*.
. Dans la zone Menu:protocoles[hôte SAN], cliquez sur le bouton *Ajouter* en regard de *hôte SAN E-Series*.
. Cliquez sur *Afficher les critères de recherche de raffinage*.
+
La section améliorer les critères de recherche s'affiche. Dans cette section, vous pouvez sélectionner le protocole qui s'applique, ainsi que d'autres critères pour la configuration, tels que le système d'exploitation, le système d'exploitation NetApp et le pilote multivoie hôte. Sélectionnez les critères que vous savez que vous voulez pour votre configuration, puis voyez quels éléments de configuration compatibles s'appliquent. Si nécessaire, effectuez les mises à jour de votre système d'exploitation et de votre protocole qui sont prescrits dans l'outil. Les informations détaillées concernant la configuration choisie sont accessibles sur la page Afficher les configurations prises en charge en cliquant sur la flèche de droite.

. Au besoin, effectuez les mises à jour de votre système d'exploitation et de votre protocole, comme indiqué dans le tableau.
+
|===
| Mises à jour du système d'exploitation | Protocole | Mises à jour liées aux protocoles 


 a| 
Vous devrez peut-être installer des pilotes prêts à l'emploi afin de vous assurer que les fonctionnalités et la prise en charge sont correctes.

Chaque fournisseur HBA dispose de méthodes spécifiques pour mettre à jour le code d'amorçage et le micrologiciel. Reportez-vous à la section support du site Web du fournisseur pour obtenir les instructions et les logiciels nécessaires à la mise à jour du code d'amorçage et du micrologiciel de l'adaptateur HBA.
 a| 
FC
 a| 
Pilote, micrologiciel et code d'amorçage de l'adaptateur de bus hôte (HBA)



 a| 
ISCSI
 a| 
Pilote, micrologiciel et code d'amorçage de la carte d'interface réseau (NIC).



 a| 
SAS
 a| 
Pilote, micrologiciel et code d'amorçage de l'adaptateur de bus hôte (HBA)

|===

