---
permalink: upgrade-controllers/install-controllers-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E4000, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, installing new controller, install new controller, install battery, installing battery, install controller canister 
summary: Après avoir retiré les anciens contrôleurs, vous pouvez installer de nouveaux contrôleurs dans le plateau du lecteur de contrôleur 
---
= Installez de nouveaux contrôleurs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après avoir retiré les anciens contrôleurs, vous pouvez installer de nouveaux contrôleurs dans le plateau du lecteur de contrôleur

.Description de la tâche
Effectuez les opérations suivantes pour chaque contrôleur du plateau du lecteur de contrôleur Si vous mettez à niveau les contrôleurs dans un plateau de lecteur de contrôleur duplex, répétez toutes les étapes pour installer le second boîtier de contrôleur.

.Avant de commencer
Assurez-vous de disposer des éléments suivants :

* Un bracelet antistatique ou prendre d'autres précautions antistatiques.
* Une batterie provenant du boîtier du contrôleur d'origine ou une batterie neuve que vous avez commandée.
* Le nouveau boîtier du contrôleur.




== Étape 1 : installer la batterie

Installez la batterie que vous avez retirée du boîtier du contrôleur d'origine ou une batterie neuve que vous avez commandée.

.Étapes
. Déballez le nouveau boîtier du contrôleur et placez-le sur une surface plane et sans électricité statique de sorte que le couvercle amovible soit orienté vers le haut.
. Appuyez sur le bouton du capot et faites glisser le capot pour le retirer.
. Orientez le boîtier du contrôleur de manière à ce que le logement de la batterie soit orienté vers vous.
. Insérez la batterie dans le nouveau boîtier du contrôleur.
+
Faites glisser la batterie dans le réservoir, en vous assurant qu'elle reste sous les rivets sur le mur de la nouvelle cartouche.

+
.. En maintenant la poignée de verrouillage à un angle de 45 degrés, alignez les connecteurs situés au bas de la batterie avec les connecteurs situés sur le boîtier.
.. Poussez la batterie vers le bas jusqu'à ce que vous entendiez un déclic, puis déplacez la poignée de verrouillage vers le haut pour fixer la batterie du contrôleur au boîtier du contrôleur.
+

TIP: Pour vous assurer que la batterie du contrôleur est correctement insérée dans le plateau du lecteur du contrôleur E5XX, vous devrez peut-être la faire glisser et la réinsérer. Il est sécurisé lorsque vous entendez un clic en place et que la poignée de verrouillage ne se déplace pas en position verticale lorsque vous l'agitez.

.. Réinstallez le capot supérieur sur le nouveau boîtier du contrôleur en le faisant glisser vers l'avant jusqu'à ce que les capots du loquet supérieur s'entendiez un clic.
+
Lorsque le loquet s'enclenche, le bas des crochets de verrouillage se trouve dans une fente métallique du châssis.



. Retournez le boîtier du contrôleur pour vérifier que la batterie est correctement installée.




== Étape 2 : installer un nouveau boîtier de contrôleur

Installer le nouveau boîtier de contrôleur dans le shelf de contrôleur.

.Étapes
. Faites glisser le nouveau boîtier du contrôleur complètement dans le plateau du lecteur du contrôleur Tournez les poignées de déverrouillage vers le centre du boîtier du contrôleur pour le verrouiller en place.
. Si le nouveau boîtier de contrôleur est équipé d'une carte HIC Fibre Channel ou d'une carte HIC InfiniBand, installez les émetteurs-récepteurs SFP+ (Fibre Channel) ou QSFP+ (InfiniBand) dans le boîtier du contrôleur et reconnectez les câbles hôtes.
+
En fonction des circuits intégrés impliqués dans votre mise à niveau, vous pourrez réutiliser un émetteur-récepteur SFP+ ou des émetteurs-récepteurs QSFP+ que vous avez retirés de votre ancien boîtier de contrôleur.

. Rebranchez tous les câbles entre le plateau du contrôleur et les tiroirs des disques.
+
Si la configuration du câblage du lecteur est identique à celle de vos anciens contrôleurs, utilisez les étiquettes que vous avez connectées aux câbles pour reconnecter les câbles correctement.



.Et la suite ?
Si la fonction sécurité du lecteur est activée, passez à link:upgrade-unlock-drives-task.html["Déverrouiller les lecteurs"]l' . Sinon, passez à link:complete-upgrade-controllers-task.html["Mise à niveau complète du contrôleur"].
