---
permalink: upgrade-controllers/overview-requirements-concept.html 
sidebar: sidebar 
keywords: E-Series, eseries, E4000, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, upgrade controller requirements, upgrade compatibility, upgrade SAS shelf, upgrade SAS shelves, upgrade SAS enclosures, SAS-2 to SAS-3 
summary: Consultez les conditions requises pour la mise à niveau et le remplacement des contrôleurs E-Series. 
---
= Mise à niveau
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de mettre à niveau les contrôleurs, vérifiez les points suivants.


NOTE: Pour plus d'informations sur les configurations prises en charge par chaque contrôleur E-Series, reportez-vous au https://docs.netapp.com/us-en/e-series/getting-started/learn-hardware-concept.html#e2800-models["Présentation du matériel E-Series"].



== Configuration matérielle et firmware requise

* * Mises à niveau des contrôleurs recto et recto verso*
+
Pour les tiroirs de contrôleur duplex, vous remplacez les deux contrôleurs. Pour les tiroirs de disques de contrôleur simplex, vous remplacez un contrôleur. Dans les deux cas, vous devez mettre le plateau du contrôleur hors tension Par conséquent, vous ne pouvez pas accéder aux données de la baie de stockage tant que vous n'avez pas terminé le remplacement correctement.

* *Plateaux et étagères*
+
Les baies de stockage dotées d'un tiroir contrôleur E-Series sont généralement gérées à l'aide de l'interface utilisateur de SANtricity System Manager.

* *Batteries du contrôleur*
+
Un nouveau contrôleur est livré sans batterie installée. Dans la mesure du possible, retirez la batterie de votre ancien contrôleur, puis installez-la dans le nouveau contrôleur. Toutefois, pour certaines mises à niveau du contrôleur, la batterie de l'ancien contrôleur n'est pas compatible avec le nouveau contrôleur. Dans ce cas, vous devez commander une batterie avec votre nouveau contrôleur et disposer de cette batterie avant de commencer ces tâches.

* *Mise en miroir synchrone et mise en miroir asynchrone*
+
Si votre baie de stockage participe à la mise en miroir synchrone, seules les connexions iSCSI ou Fibre Channel sont prises en charge entre le site principal et le site distant. Si la configuration de la carte d'interface hôte (HIC) de vos nouveaux contrôleurs n'inclut pas de connexions iSCSI ou Fibre Channel, la mise en miroir synchrone ne sera pas prise en charge.

+
Pour la mise en miroir asynchrone, la baie de stockage locale et la baie de stockage distante peuvent exécuter différentes versions du micrologiciel. La version minimale prise en charge est la version 7.84 du firmware SANtricity.




NOTE: Pour les contrôleurs E4000, la mise en miroir est uniquement prise en charge sur les connexions Fibre Channel.

* *Limites d'objets de stockage*
+
Si vous passez de modèles milieu de gamme à modèles d'entrée de gamme (par exemple, modèles 5 x 00 à 2 x 00), votre nouvelle configuration de baie de stockage prendra en charge un nombre inférieur de certains objets de stockage (par exemple, des volumes) dans le logiciel de gestion du stockage par rapport à votre ancienne configuration. Assurez-vous que votre ancienne configuration ne dépasse pas les limites de l'objet de stockage.

+
Voir http://hwu.netapp.com/home.aspx["Hardware Universe"^] pour plus d'informations.

* *Mise à niveau vers des modèles plus récents*
+
Si vous remplacez les contrôleurs par une mise à niveau vers un nouveau modèle, n'oubliez pas que votre baie de stockage actuelle peut disposer de fonctionnalités premium installées sur le nouveau modèle ne prend pas en charge.

+
Lorsque vous mettez à niveau votre contrôleur E-Series, vous devez désactiver les fonctionnalités premium utilisées sur votre baie de stockage qui ne sont pas prises en charge par les nouveaux contrôleurs.





== Compatibilité des mises à niveau

Examinez les chemins de mise à niveau pris en charge pour chaque modèle de baie de stockage.

[role="tabbed-block"]
====
.Compatibilité de mise à niveau du contrôleur E4000
--
[cols="h,d,d,d"]
|===
| Chemin de mise à niveau | Batterie | Prise en charge des fonctionnalités | Tiroirs SAS-3 


| De E2800 à E4000  a| 
Commandez une nouvelle batterie.
 a| 
* E4000 ne prend pas en charge l'iSCSI ARVM
* Le port de la carte de base E4000 est iSCSI uniquement et ne peut pas être modifié en FC
* E4000 ne peut prendre en charge que 300 disques
* E4000 ne peut prendre en charge que 512 volumes
* E4000 ne prend pas en charge les configurations SAS
* E4000 ne prend pas en charge les volumes de stockage distants

 a| 
Les contrôleurs E4000 doivent utiliser des tiroirs SAS-3.



| De E5700 à E4000  a| 
Commandez une nouvelle batterie.
 a| 
* E4000 ne prend pas en charge l'iSCSI ARVM
* Le port de la carte de base E4000 est iSCSI uniquement et ne peut pas être modifié en FC
* E4000 ne peut prendre en charge que 300 disques
+
** Le système E5700 peut prendre en charge jusqu'à 480 disques


* E4000 ne peut prendre en charge que 512 volumes
+
** L'E5700 peut prendre en charge jusqu'à 2048 volumes


* La prise en charge de la carte d'interface hôte InfiniBand n'est pas disponible
* E4000 ne prend pas en charge les configurations SAS

 a| 
Les contrôleurs E4000 doivent utiliser des tiroirs SAS-3.

|===
--
.Compatibilité de mise à niveau des contrôleurs EF600 et EF300
--
[cols="h,d,d,d"]
|===
| Chemin de mise à niveau | Batterie | Prise en charge des fonctionnalités | Tiroirs SAS-3 


| De EF600 à EF600 à l'aide d'une autre carte d'interface hôte  a| 
Réutiliser l'ancienne batterie.
 a| 
* Pas de prise en charge des volumes à provisionnement fin
* Pas de prise en charge mise en miroir synchrone

| Les contrôleurs EF600 doivent utiliser des tiroirs SAS-3. 


| De EF300 à EF600  a| 
Réutiliser l'ancienne batterie.
 a| 
* Pas de prise en charge des volumes à provisionnement fin
* Pas de prise en charge mise en miroir synchrone

 a| 
Les contrôleurs EF600 doivent utiliser des tiroirs SAS-3.

|===
--
.Compatibilité des mises à niveau des contrôleurs existants
--
[cols="h,d,d,d,d"]
|===
| Chemin de mise à niveau | Batterie | ID du fournisseur | Prise en charge des fonctionnalités | Tiroirs SAS-3 


| De E2x00 à E2x00  a| 
Réutiliser l'ancienne batterie.
 a| 
Étapes supplémentaires requises.
 a| 
Les snapshots hérités ne sont pas pris en charge sur la baie E2700.
 a| 
Les contrôleurs E2800 ne doivent pas être placés en tiroirs SAS-2.



| De E2x00 à E5x00  a| 
Commandez une nouvelle batterie.
 a| 
Des étapes supplémentaires sont nécessaires lors de la mise à niveau de E2600 vers E5500 ou E5600 ou lors d'une mise à niveau de E2700 vers E5400.
 a| 
* Les snapshots hérités ne sont pas pris en charge sur la baie E5500 ou E5600.
* La mise en miroir de volume distant existant (RVM) n'est pas prise en charge sur les baies E5500 ou E5600 avec des HIC iSCSI.
* Data assurance n'est pas pris en charge sur les baies E5500 ou E5600 avec circuits intégrés iSCSI.
* Les contrôleurs E5700 ne doivent pas être placés dans des tiroirs SAS-2.

 a| 
Les contrôleurs E5400, E5500 et E5600 ne doivent pas être placés dans des tiroirs SAS-3.



| De E5x00 à E2x00  a| 
Commandez une nouvelle batterie.
 a| 
Des étapes supplémentaires sont nécessaires lors de la mise à niveau d'une baie E5500 ou d'une baie E5600 vers une baie E2600 ou lors d'une mise à niveau de la baie E5400 vers une baie E2700.
 a| 
Les snapshots hérités ne sont pas pris en charge sur la baie E2700.
 a| 
Les contrôleurs 5400, E5500 et E5600 ne doivent pas être placés dans des tiroirs SAS-3.



| De E5x00 à E5x00  a| 
Réutiliser l'ancienne batterie.
 a| 
Étapes supplémentaires requises pour la mise à niveau de E5400 vers E5500 ou E5600.
 a| 
* Les snapshots hérités ne sont pas pris en charge sur la baie E5500 ou E5600.
* La mise en miroir de volume distant existant (RVM) n'est pas prise en charge sur les systèmes E5400 ou E5500 avec des HIC iSCSI.
* Data assurance n'est pas pris en charge sur les systèmes E5400 ou E5500 avec des circuits intégrés iSCSI.
* Les contrôleurs E5700 ne doivent pas être placés dans des tiroirs SAS-2.

 a| 
Les contrôleurs E5400, E5500 et E5600 ne doivent pas être placés dans des tiroirs SAS-3.



| De l'EF540 à l'EF540  a| 
Réutiliser l'ancienne batterie.
 a| 
Étapes supplémentaires requises pour la mise à niveau d'une baie EF540 vers une baie EF550 ou EF560.
 a| 
* Pas de snapshots existants pour la baie EF550/EF560.
* Pas de Data assurance pour la baie EF550/EF560 avec iSCSI.
* Les contrôleurs EF570 ne doivent pas être placés en tiroirs SAS-3.

 a| 
Les contrôleurs EF540, EF550 et EF560 ne doivent pas être placés dans des tiroirs SAS-3.

|===
--
====


== Armoires SAS

Le système E5700 prend en charge les boîtiers SAS-2 DE5600 et DE6600 par le biais d'une mise à niveau de la tête. Lorsqu'un contrôleur E5700 est installé dans des armoires SAS-2, la prise en charge des ports hôte de base est désactivée.

|===
| Tiroirs SAS-2 | Tiroirs SAS-3 


 a| 
Les tiroirs SAS-2 incluent les modèles suivants :

* Tiroirs disques DE1600, DE5600 et DE6600
* Tiroirs disques du contrôleur E5400, E5500 et E5600
* Baies Flash EF540, EF550 et EF560
* Tiroirs disques de contrôleur E2600 et E2700

 a| 
Les tiroirs SAS-3 incluent les modèles suivants :

* Tiroirs contrôleurs E4000
* Tiroirs contrôleurs EF600 ^1^
* Tiroirs contrôleurs EF300 ^1^
* Tiroirs contrôleurs E2800
* Tiroirs contrôleurs E5700
* Tiroirs disques DE212C, DE224C, DE460C


|===
Remarques :

. Les contrôleurs EF600 et EF300 peuvent uniquement utiliser des tiroirs SAS-3 pour les extensions.




== Protection des investissements SAS-2 vers SAS-3

Vous pouvez reconfigurer votre système SAS-2 pour qu'il soit utilisé derrière un nouveau tiroir de contrôleur SAS-3 (E57XX/EF570/E28XX).


NOTE: Cette procédure nécessite une demande FPVR (Feature Product variance Request). Pour déposer une FPVR, contactez votre équipe de vente.
