---
permalink: upgrade-controllers/prepare-upgrade-controllers-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, upgrade controller requirements, upgrade controller key management, prepare upgrade controller, upgrade controller preparation, preparing controller upgrade 
summary: Préparez la mise à niveau des contrôleurs en enregistrant la clé de sécurité du disque, en rassemblant les données de support et en mettant le contrôleur hors ligne. 
---
= Préparation à la mise à niveau des contrôleurs
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Préparez la mise à niveau des contrôleurs en enregistrant la clé de sécurité du lecteur (si utilisée), en enregistrant le numéro de série, en recueillant des données de support, en désactivant certaines fonctions (si utilisées) et en mettant le contrôleur hors ligne.


NOTE: La collecte des données de support peut affecter temporairement les performances de votre baie de stockage.

.Étapes
. Assurez-vous que la baie de stockage existante est mise à jour vers la dernière version du système d'exploitation disponible pour vos contrôleurs actuels. Dans SANtricity System Manager, accédez au menu :support[Upgrade Center] pour afficher l'inventaire de vos logiciels et micrologiciels.
+

NOTE: Si vous effectuez une mise à niveau vers des contrôleurs prenant en charge SANtricity OS version 8.50, vous devez installer les dernières versions de SANtricity OS et de la dernière NVSRAM après avoir installé et mis sous tension les nouveaux contrôleurs. Si vous n'effectuez pas cette mise à niveau, il se peut que vous ne puissiez pas configurer la matrice de stockage pour l'équilibrage automatique de la charge (ALB).

. Si vous avez installé des lecteurs sécurisés et que vous prévoyez d'effectuer un remplacement complet du contrôleur, reportez-vous au tableau suivant pour effectuer les étapes appropriées de votre type de sécurité (interne ou externe) et de l'état du disque. Si vous n'avez pas *pas* de lecteurs sécurisés installés, vous pouvez ignorer cette étape et passer à l'étape 3 sous le tableau.
+

NOTE: Certaines étapes du tableau nécessitent l'utilisation des commandes de l'interface de ligne de commande. Pour plus d'informations sur l'utilisation de ces commandes, reportez-vous au https://docs.netapp.com/us-en/e-series-cli/index.html["Référence de l'interface de ligne de commande"].

+
|===
| Type et contexte de sécurité | Étapes 


 a| 
Gestion interne des clés, un ou plusieurs disques verrouillés
 a| 
Exportez le fichier de clé de sécurité interne vers un emplacement connu du client de gestion (le système avec un navigateur utilisé pour accéder à System Manager). Utilisez le `export storageArray securityKey` Commande CLI. Vous devez fournir la phrase de passe associée à la clé de sécurité et spécifier l'emplacement où vous souhaitez enregistrer la clé.



 a| 
Gestion externe des clés, tous les disques verrouillés, ce dernier peut passer temporairement à une gestion interne des clés pour le remplacement du contrôleur (recommandé).
 a| 
Effectuez les opérations suivantes dans l'ordre :

.. Enregistrez l'adresse du serveur KMS externe et le numéro de port. Dans System Manager, accédez au menu:Paramètres[système > gestion des clés de sécurité > Afficher/Modifier les paramètres du serveur de gestion des clés].
.. Assurez-vous que les certificats client et serveur sont disponibles sur votre hôte local afin que la matrice de stockage et le serveur de gestion des clés puissent s'authentifier une fois le remplacement du contrôleur terminé. Utilisez le `save storageArray keyManagementCertificate` Commande CLI pour enregistrer les certificats. Veillez à exécuter la commande deux fois, une fois avec le `certificateType` paramètre défini sur `client`, et l'autre avec le paramètre défini sur `server`.
.. Transition vers la gestion interne des clés en exécutant le système `disable storageArray externalKeyManagement` Commande CLI.
.. Exportez le fichier de clé de sécurité interne vers un emplacement connu du client de gestion (le système avec un navigateur utilisé pour accéder à System Manager). Utilisez le `export storageArray securityKey` Commande CLI. Vous devez fournir la phrase de passe associée à la clé de sécurité et spécifier l'emplacement où vous souhaitez enregistrer la clé.




 a| 
Gestion externe des clés, tous les disques verrouillés, vous ne pouvez *pas* passer à une gestion interne des clés pour le remplacement du contrôleur.
 a| 
Effectuez les opérations suivantes dans l'ordre :

.. Enregistrez l'adresse du serveur KMS externe et le numéro de port. Dans System Manager, accédez au menu:Paramètres[système > gestion des clés de sécurité > Afficher/Modifier les paramètres du serveur de gestion des clés].
.. Assurez-vous que les certificats client et serveur sont disponibles sur votre hôte local afin que la matrice de stockage et le serveur de gestion des clés puissent s'authentifier une fois le remplacement du contrôleur terminé. Utilisez le `save storageArray keyManagementCertificate` Commande CLI pour enregistrer les certificats. Veillez à exécuter la commande deux fois, une fois avec le `certificateType` paramètre défini sur `client`, et l'autre avec le paramètre défini sur `server`.
.. Exportez le fichier de clé de sécurité interne vers un emplacement connu du client de gestion (le système avec un navigateur utilisé pour accéder à System Manager). Utilisez le `export storageArray securityKey` Commande CLI. Vous devez fournir la phrase de passe associée à la clé de sécurité et spécifier l'emplacement où vous souhaitez enregistrer la clé.




 a| 
Gestion externe des clés, disques partiels verrouillés
 a| 
Aucune étape supplémentaire n'est nécessaire.

|===
+

NOTE: Votre matrice de stockage doit être dans un état optimal pour récupérer les certificats client et serveur. Si les certificats ne peuvent pas être récupérés, vous devez créer une nouvelle RSC, obtenir la signature CSR et télécharger le certificat du serveur à partir du serveur de gestion de clés externe (EKMS).

. Notez le numéro de série de votre matrice de stockage :
+
.. Dans System Manager, sélectionnez menu :support[Centre de support > onglet Ressources de support].
.. Faites défiler vers le bas jusqu'à *lancer les informations détaillées de la matrice de stockage*, puis sélectionnez *profil de la matrice de stockage*.
+
Le rapport s'affiche à l'écran.

.. Pour localiser le numéro de série du châssis sous le profil de la matrice de stockage, saisissez *numéro de série* dans la zone de texte *Rechercher*, puis cliquez sur *Rechercher*.
+
Tous les termes correspondants sont mis en évidence. Pour faire défiler tous les résultats un par un, continuez à cliquer sur *Rechercher*.

.. Enregistrer le `Chassis Serial Number`.
+
Vous avez besoin de ce numéro de série pour effectuer les étapes du link:complete-upgrade-controllers-task.html["Mise à niveau complète du contrôleur"].



. Rassemblez les données de support relatives à votre baie de stockage à l'aide de l'interface utilisateur graphique ou de l'interface de ligne de commande :
+
** Utilisez System Manager ou la fenêtre de gestion de baie dans Storage Manager pour collecter et enregistrer un pack de support de votre baie de stockage.
+
*** Dans System Manager, sélectionnez menu :support [support Center > onglet Diagnostics]. Sélectionnez ensuite *Collect support Data* et cliquez sur *collect*.
*** Dans la barre d'outils de la fenêtre gestion des matrices, sélectionnez menu:Monitor[Health > Collect support Data Manually]. Entrez ensuite un nom et spécifiez un emplacement sur votre système où vous souhaitez stocker le bundle de support.
+
Le fichier est enregistré dans le dossier Téléchargements de votre navigateur portant le nom `support-data.7z`.

+
Si votre tiroir contient des tiroirs, les données de diagnostic correspondant à ce tiroir sont archivées dans un fichier compressé distinct nommé `tray-component-state-capture.7z`.



** Utilisez l'interface de ligne de commande pour exécuter le `save storageArray supportData` commande pour collecter des données de support complètes sur la baie de stockage.


. Assurez-vous qu'aucune opération d'E/S n'est en cours entre la matrice de stockage et tous les hôtes connectés :
+
.. Arrêtez tous les processus qui impliquent les LUN mappées du stockage vers les hôtes.
.. Assurez-vous qu'aucune application n'écrit de données sur les LUN mappées du stockage aux hôtes.
.. Démontez tous les systèmes de fichiers associés aux volumes de la baie.
+

NOTE: Les étapes exactes permettant d'arrêter les opérations d'E/S de l'hôte dépendent du système d'exploitation hôte et de la configuration, qui dépassent le cadre de ces instructions. Si vous ne savez pas comment arrêter les opérations d'E/S des hôtes dans votre environnement, essayez d'arrêter l'hôte.

+

CAUTION: *Perte de données possible* -- si vous continuez cette procédure pendant les opérations d'E/S, vous risquez de perdre des données.



. Si la baie de stockage participe à une relation de mise en miroir, arrêtez toutes les opérations d'E/S hôte sur la baie de stockage secondaire.
. Si vous utilisez la mise en miroir asynchrone ou synchrone, supprimez les paires en miroir et désactivez les relations de mise en miroir via System Manager ou la fenêtre Array Management.
. Si un volume à provisionnement fin est signalé à l'hôte comme étant un volume fin et que l'ancienne baie exécute un micrologiciel (micrologiciel 8.25 ou supérieur) prenant en charge la fonctionnalité UNMAP, désactivez la mise en cache d'écriture différée pour tous les volumes fins :
+
.. Dans System Manager, sélectionnez menu :Storage[volumes].
.. Sélectionnez un volume, puis sélectionnez menu:autres [Modifier les paramètres du cache].
+
La boîte de dialogue Modifier les paramètres de cache s'affiche. Tous les volumes de la matrice de stockage s'affichent dans cette boîte de dialogue.

.. Sélectionnez l'onglet *Basic* et modifiez les paramètres de mise en cache de lecture et d'écriture.
.. Cliquez sur *Enregistrer*.
.. Attendez cinq minutes pour permettre au disque d'avoir transféré toutes les données de la mémoire cache.


. Si le langage SAML est activé sur le contrôleur, contactez le support technique pour désactiver l'authentification SAML.
+

NOTE: Une fois le langage SAML activé, vous ne pouvez pas le désactiver via l'interface de SANtricity System Manager. Pour désactiver la configuration SAML, contactez le support technique pour obtenir de l'aide.

. Attendre la fin de toutes les opérations en cours avant de passer à l'étape suivante.
+
.. Dans la page *Home* de System Manager, sélectionnez *Afficher les opérations en cours*.
.. Assurez-vous que toutes les opérations affichées dans la fenêtre *opérations en cours* sont terminées avant de continuer.


. Mettez le plateau du contrôleur hors tension
+
Attendez que tous les voyants du plateau du contrôleur s'allument.

. Coupez l'alimentation de chaque plateau de lecteur connecté au plateau du contrôleur
+
Attendez deux minutes que tous les disques soient arrêtés.



.Et la suite ?
Accédez à link:remove-controllers-task.html["Supprimer les contrôleurs"].
