---
permalink: upgrade-controllers/upgrade-unlock-drives-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, unlock drives, key management, Drive Security, 
summary: Si vous mettez à niveau les contrôleurs E2800 et E5700 alors que la fonction sécurité des disques est activée, vous devez déverrouiller manuellement les disques. 
---
= Exploitez tout le potentiel des disques E-Series
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La fonction de sécurité du lecteur de ces contrôleurs verrouille les lecteurs partiellement, en externe ou en interne. Si la fonction sécurité du lecteur est activée, vous devez déverrouiller manuellement ces lecteurs.

Suivre la procédure appropriée pour :

* <<Gestion interne des clés>>
* <<Gestion externe des clés>>




== Gestion interne des clés

Procédez comme suit pour la gestion interne des clés lorsque tous les disques sont verrouillés.

.Description de la tâche
Les contrôleurs récemment échangés se verrouillent avec un code d'affichage à sept segments de *L5*. Ce verrouillage se produit lorsqu'aucun lecteur ne peut effectuer la synchronisation de code automatique (ACS). Une fois la clé de sécurité importée, ACS reprend et met à jour les nouveaux contrôleurs.


NOTE: Si vous n'utilisez pas le port de gestion 1, essayez avec d'autres adresses IP par défaut : + Ctrl A port 1 : 169.254.128.101 + Ctrl A port 2 : 169.254.128.102 + Ctrl B port 1 : 169.254.128.101 + Ctrl B port 2 : 169.254.128.102

.Étapes
. Établir une connexion ethernet directe et privée entre la baie de stockage et l'ordinateur portable ou le PC du client SANtricity. Pour cela :
+
.. Utilisez un câble ethernet RJ45 pour connecter l'ordinateur portable au port de gestion 1 du contrôleur A.
.. Pour terminer la connexion, vous devrez peut-être affecter l'ordinateur portable à une adresse IP dans le même sous-réseau que le contrôleur A. pendant le verrouillage du contrôleur, le contrôleur A prend par défaut l'adresse de gestion 169.254.128.101. Vous pouvez donc attribuer l'ordinateur portable à un sous-réseau tel que « 169.254.128.201 ».


. En utilisant l'adresse IP 169.254.128.101 avec le nom d'utilisateur *admin* et le mot de passe vide, importez la clé interne à l'aide de `import storageArray securityKey file` la commande CLI, avec la clé de sécurité enregistrée à partir de link:prepare-upgrade-controllers-task.html["Préparation à la mise à niveau des contrôleurs"]. Pour plus d'informations sur l'utilisation de cette commande, reportez-vous au https://docs.netapp.com/us-en/e-series-cli/index.html["Référence de l'interface de ligne de commande"] .
+
*Exemple :* `SMcli 169.254.128.101 -k -u admin -p "" -c "import storageArray securityKey file=\"Directory&FileName\" passPhrase=\"passPhraseString\";"`

+
Vous pouvez également importer la clé interne via l'API REST via l'appel suivant : `/storage-systems/{system-id}/security-key/import`



Les contrôleurs continueront le processus de synchronisation par code automatique à partir des lecteurs et redémarrent. Après le redémarrage, les contrôleurs seront accessibles via la configuration IP d'origine.



== Gestion externe des clés

Procédez comme suit pour gérer les clés externes lorsque tous les disques sont verrouillés.

.Description de la tâche
Les contrôleurs récemment échangés se verrouillent avec un code d'affichage à sept segments de *L5*. Ce verrouillage se produit lorsqu'aucun lecteur ne peut effectuer la synchronisation de code automatique (ACS). Une fois la clé de sécurité importée, ACS reprend et met à jour les nouveaux contrôleurs.

.Étapes
. Établir une connexion ethernet directe et privée entre la baie de stockage et l'ordinateur portable ou le PC du client SANtricity. Pour cela :
+
.. Utilisez un câble ethernet RJ45 pour connecter l'ordinateur portable au port de gestion 1 du contrôleur A.
.. Pour terminer la connexion, vous devrez peut-être affecter l'ordinateur portable à une adresse IP dans le même sous-réseau que le contrôleur A. pendant le verrouillage du contrôleur, le contrôleur A prend par défaut l'adresse de gestion 169.254.128.101. Vous pouvez donc attribuer l'ordinateur portable à un sous-réseau tel que « 169.254.128.201 ».


. À l'aide de la clé de sécurité enregistrée link:prepare-upgrade-controllers-task.html["Préparation à la mise à niveau des contrôleurs"]à partir de , importez la clé externe à l'adresse IP 169.254.128.101 avec le nom d'utilisateur *admin* et le mot de passe restant vide.
+
*Exemple :* `SMcli 169.254.128.101 -k -u admin -p "" -c "import storageArray securityKey file=\"Directory&FileName\" passPhrase=\"passPhraseString\";"`

+
Vous pouvez également importer la clé externe via l'API REST via l'appel suivant : `/storage-systems/{system-id}/security-key/import`

+
Les contrôleurs continueront le processus de synchronisation par code automatique à partir des lecteurs et redémarrent. Après le redémarrage, les contrôleurs seront accessibles via la configuration IP d'origine.

. (Facultatif) si nécessaire, les lecteurs peuvent être re-codés en effectuant les opérations suivantes :
+
*Exemple :* `SMcli <original_controller _ip> -u admin -p "<original_array_password>" -c "create storageArray securityKey" passPhrase=\"passPhraseString\" file=\"filename\";”`


