---
permalink: upgrade-santricity/upgrade-multiple-controller-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, SANtricity, drive firmware, upgrade SANtricity, upgrade OS, upgrade E-Series, upgrade firmware, upgrading, upgrade IOM firmware, upgrade NVSRAM, upgrade controller 
summary: Utilisez SANtricity Unified Manager pour mettre à niveau le logiciel SANtricity OS sur plusieurs baies de stockage de même type. 
---
= Mise à niveau des logiciels et des firmwares pour plusieurs contrôleurs
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez mettre à niveau plusieurs contrôleurs du même type avec SANtricity Unified Manager.

.Avant de commencer
* Révision link:overview-upgrade-consider-task.html["Mise à niveau"].
* Déterminez si vous souhaitez activer votre mise à niveau logicielle dès maintenant ou ultérieurement. Vous pouvez choisir de l'activer ultérieurement pour les raisons suivantes :
+
** *Temps de jour* -- l'activation du logiciel peut prendre un certain temps, vous pouvez donc attendre que les charges d'E/S soient plus légères. Les contrôleurs basculent pendant l'activation, tout comme les performances peuvent être inférieures à la normale jusqu'à la fin de la mise à niveau.
** *Type de paquet* -- vous pouvez tester le nouveau logiciel de système d'exploitation sur une matrice de stockage avant de mettre à niveau les fichiers sur d'autres matrices de stockage.


* Prenez connaissance des précautions suivantes :



CAUTION: Risque de perte de données ou de détérioration de la baie de stockage. Ne modifiez pas la baie de stockage pendant la mise à niveau. Maintenez l'alimentation de la baie de stockage.


CAUTION: Si vous mettez à niveau le système d'exploitation SANtricity sur une appliance StorageGRID (SG5612 ou SG5760, par exemple), vous devez interrompre les activités d'E/S en plaçant l'appliance en mode de maintenance avant de poursuivre cette procédure, sinon les données risquent d'être perdues. Pour obtenir des instructions détaillées, reportez-vous aux instructions d'installation et de maintenance de votre appliance StorageGRID.



== Étape 1 : effectuer une vérification préalable de l'état de santé de la mise à niveau

Une vérification de l'état s'exécute dans le cadre du processus de mise à niveau, mais vous pouvez également effectuer une vérification de l'état séparément avant de commencer. Le contrôle de l'état des composants de la baie de stockage vérifie que la mise à niveau peut se poursuivre.

.Étapes
. Ouvrez Unified Manager.
. Dans la vue principale, sélectionnez *Manage*, puis menu:Upgrade Center[Pre-Upgrade Health Check].
+
La boîte de dialogue Vérification préalable à la mise à niveau s'ouvre et répertorie tous les systèmes de stockage détectés.

. Si nécessaire, filtrez ou triez les systèmes de stockage dans la liste pour afficher tous les systèmes qui ne sont pas actuellement dans l'état optimal.
. Cochez les cases des systèmes de stockage que vous souhaitez exécuter via la vérification de l'état.
. Cliquez sur *Démarrer*.
+
La progression s'affiche dans la boîte de dialogue pendant la vérification de l'état.

. Lorsque le contrôle d'intégrité est terminé, vous pouvez cliquer sur les points de suspension (...) à droite de chaque ligne pour afficher plus d'informations et effectuer d'autres tâches.
+

NOTE: Si l'une des baies ne fonctionne pas, vous pouvez ignorer cette matrice et poursuivre la mise à niveau pour les autres, ou arrêter le processus complet et dépanner les baies qui ne sont pas utilisées.





== Étape 2 : téléchargement de fichiers logiciels à partir du site d'assistance

Cette étape vous permet de vous rendre sur le site de support NetApp pour enregistrer les nouveaux fichiers logiciels DLP (téléchargeable) sur votre système hôte de gestion.

.Étapes
. Si votre matrice de stockage ne contient qu'un seul contrôleur ou qu'un pilote multivoie n'est pas utilisé, arrêtez l'activité d'E/S vers la matrice de stockage pour éviter les erreurs d'application. Si votre baie de stockage est équipée de deux contrôleurs et qu'un pilote multivoie est installé, il n'est pas nécessaire d'arrêter l'activité d'E/S.
. Dans la vue principale de Unified Manager, sélectionnez *Manage*, puis une ou plusieurs baies de stockage à mettre à niveau.
. Sélectionnez menu:Centre de mise à niveau [mise à niveau du logiciel SANtricity OS].
+
La page mise à niveau du logiciel SANtricity OS s'affiche.

. Téléchargez le pack logiciel SANtricity OS le plus récent du site de support NetApp sur votre machine locale.
+
.. Cliquez sur *Ajouter un nouveau fichier au référentiel logiciel*.
.. Cliquez sur le lien pour trouver les derniers téléchargements *SANtricity OS*.
.. Cliquez sur le lien *Télécharger la dernière version*.
.. Suivez les instructions restantes pour télécharger le fichier SANtricity OS et le fichier NVSRAM sur votre ordinateur local.


+

NOTE: Un firmware avec signature numérique est requis dans la version 8.42 et supérieure. Si vous tentez de télécharger un firmware non signé, une erreur s'affiche et le téléchargement est interrompu.





== Étape 3 : transfert de fichiers logiciels vers les contrôleurs

Vous chargez le fichier logiciel du système d'exploitation SANtricity et le fichier NVSRAM dans le référentiel de façon à ce qu'il soit accessible au Centre de mise à niveau d'Unified Manager.


CAUTION: Risque de perte de données ou de détérioration de la baie de stockage. Ne modifiez pas la baie de stockage pendant la mise à niveau. Maintenez l'alimentation de la baie de stockage.

.Étapes
. Dans la vue principale de Unified Manager, sélectionnez *Manage*, puis une ou plusieurs baies de stockage à mettre à niveau.
. Sélectionnez menu:Centre de mise à niveau [mise à niveau du logiciel SANtricity OS].
+
La page mise à niveau du logiciel SANtricity OS s'affiche.

. Téléchargez le pack logiciel SANtricity OS le plus récent du site de support NetApp sur votre machine locale.
+
.. Cliquez sur *Ajouter un nouveau fichier au référentiel logiciel*.
.. Cliquez sur le lien pour trouver les derniers téléchargements *SANtricity OS*.
.. Cliquez sur le lien *Télécharger la dernière version*.
.. Suivez les instructions restantes pour télécharger le fichier SANtricity OS et le fichier NVSRAM sur votre ordinateur local.


+

NOTE: Un firmware avec signature numérique est requis dans la version 8.42 et supérieure. Si vous tentez de télécharger un firmware non signé, une erreur s'affiche et le téléchargement est interrompu.

. Sélectionnez le fichier du logiciel OS et le fichier NVSRAM que vous souhaitez utiliser pour mettre à niveau les contrôleurs :
+
.. Dans la liste déroulante *sélectionnez un fichier logiciel SANtricity OS*, sélectionnez le fichier OS que vous avez téléchargé sur votre ordinateur local.
+
Si plusieurs fichiers sont disponibles, les fichiers sont triés de la date la plus récente à la date la plus ancienne.

+

NOTE: Le référentiel logiciel répertorie tous les fichiers logiciels associés au proxy de services Web. Si vous ne voyez pas le fichier que vous souhaitez utiliser, vous pouvez cliquer sur le lien *Ajouter un nouveau fichier au référentiel logiciel* pour accéder à l'emplacement où réside le fichier OS que vous souhaitez ajouter.

.. Dans la liste déroulante *Sélectionner un fichier NVSRAM*, sélectionnez le fichier de contrôleur que vous souhaitez utiliser.
+
S'il existe plusieurs fichiers, les fichiers sont triés de la date la plus récente à la date la plus ancienne.



. Dans le tableau matrice de stockage compatible, vérifiez les matrices de stockage compatibles avec le fichier logiciel du système d'exploitation que vous avez sélectionné, puis sélectionnez les matrices que vous souhaitez mettre à niveau.
+
** Les matrices de stockage que vous avez sélectionnées dans la vue gestion et compatibles avec le fichier de micrologiciel sélectionné sont sélectionnées par défaut dans la table matrice de stockage compatible.
** Les matrices de stockage qui ne peuvent pas être mises à jour avec le fichier de micrologiciel sélectionné ne peuvent pas être sélectionnées dans le tableau matrice de stockage compatible comme indiqué par l'état *incompatible*.


. (Facultatif) pour transférer le fichier logiciel vers les matrices de stockage sans les activer, cochez la case *transférer le logiciel OS vers les matrices de stockage, le marquer comme étant par étape et l'activer ultérieurement*.
. Cliquez sur *Démarrer*.
. Selon que vous choisissez d'activer maintenant ou ultérieurement, effectuez l'une des opérations suivantes :
+
** Tapez *TRANSFER* pour confirmer que vous souhaitez transférer les versions du logiciel OS proposées sur les baies que vous avez sélectionnées pour la mise à niveau, puis cliquez sur *Transfer*.
+
Pour activer le logiciel transféré, sélectionnez menu:Centre de mise à niveau [Activer le logiciel OS par étapes].

** Tapez *UPGRADE* pour confirmer que vous souhaitez transférer et activer les versions de logiciel de système d'exploitation proposées sur les baies que vous avez sélectionnées pour la mise à niveau, puis cliquez sur *Upgrade*.
+
Le système transfère le fichier logiciel vers chaque matrice de stockage que vous avez sélectionnée pour la mise à niveau, puis active ce fichier en lançant un redémarrage.



+
Les actions suivantes se produisent pendant l'opération de mise à niveau :

+
** Une vérification de l'état de pré-mise à niveau s'effectue dans le cadre du processus de mise à niveau. Un contrôle avant la mise à niveau de l'état de santé vérifie tous les composants de la baie de stockage afin de vérifier que la mise à niveau peut se faire.
** Si une vérification de l'état d'intégrité d'une matrice de stockage échoue, la mise à niveau s'arrête. Vous pouvez cliquer sur les points de suspension (...) et sélectionner *Enregistrer le journal* pour examiner les erreurs. Vous pouvez également choisir de remplacer l'erreur de vérification d'intégrité, puis de cliquer sur *Continuer* pour poursuivre la mise à niveau.
** Vous pouvez annuler l'opération de mise à niveau après la vérification de l'état de santé avant la mise à niveau.


. (Facultatif) une fois la mise à niveau terminée, vous pouvez afficher la liste des mises à niveau pour une matrice de stockage spécifique en cliquant sur les points de suspension (...), puis en sélectionnant *Enregistrer le journal*.
+
Le fichier est enregistré dans le dossier Téléchargements de votre navigateur portant le nom``upgrade_log-<date>.json``.





== Étape 4 : activation des fichiers logiciels par étapes (facultatif)

Vous pouvez choisir d'activer le fichier logiciel immédiatement ou attendre jusqu'à ce qu'il soit plus pratique. Cette procédure suppose que vous avez choisi d'activer le fichier logiciel ultérieurement.


NOTE: Vous ne pouvez pas arrêter le processus d'activation après son démarrage.

.Étapes
. Dans la vue principale de Unified Manager, sélectionnez *gérer*. Si nécessaire, cliquez sur la colonne État pour trier toutes les matrices de stockage avec l'état « mise à niveau du système d'exploitation (en attente d'activation) ».
. Sélectionnez une ou plusieurs baies de stockage pour lesquelles vous souhaitez activer le logiciel, puis sélectionnez menu :Centre de mise à niveau [Activer le système d'exploitation par étapes].
+
Les actions suivantes se produisent pendant l'opération de mise à niveau :

+
** Une vérification de l'état de santé de pré-mise à niveau s'exécute dans le cadre du processus d'activation. Le contrôle préalable à la mise à niveau de l'état de santé vérifie tous les composants de la baie de stockage pour s'assurer que l'activation peut continuer.
** Si un contrôle d'intégrité échoue pour une matrice de stockage, l'activation s'arrête. Vous pouvez cliquer sur les points de suspension (...) et sélectionner *Enregistrer le journal* pour examiner les erreurs. Vous pouvez également choisir de remplacer l'erreur de vérification de l'état, puis de cliquer sur *Continuer* pour poursuivre l'activation.
** Vous pouvez annuler l'opération d'activation après la vérification de l'état de fonctionnement avant la mise à niveau. Une fois la vérification préalable à la mise à niveau terminée, l'activation a lieu. Le temps nécessaire à l'activation dépend de la configuration de la matrice de stockage et des composants que vous activez.


. (Facultatif) une fois l'activation terminée, vous pouvez afficher une liste des éléments activés pour une matrice de stockage spécifique en cliquant sur les points de suspension (...), puis en sélectionnant *Enregistrer le journal*.
+
Le fichier est enregistré dans le dossier Téléchargements de votre navigateur portant le nom `activate_log-<date>.json`.



.Et la suite ?
La mise à niveau du logiciel du contrôleur est terminée. Vous pouvez reprendre les opérations normales.
